// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module generate_binary_matr_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        matrix_0_address0,
        matrix_0_ce0,
        matrix_0_we0,
        matrix_0_d0,
        matrix_1_address0,
        matrix_1_ce0,
        matrix_1_we0,
        matrix_1_d0,
        matrix_2_address0,
        matrix_2_ce0,
        matrix_2_we0,
        matrix_2_d0,
        matrix_3_address0,
        matrix_3_ce0,
        matrix_3_we0,
        matrix_3_d0,
        matrix_4_address0,
        matrix_4_ce0,
        matrix_4_we0,
        matrix_4_d0,
        matrix_5_address0,
        matrix_5_ce0,
        matrix_5_we0,
        matrix_5_d0,
        matrix_6_address0,
        matrix_6_ce0,
        matrix_6_we0,
        matrix_6_d0,
        matrix_7_address0,
        matrix_7_ce0,
        matrix_7_we0,
        matrix_7_d0,
        matrix_8_address0,
        matrix_8_ce0,
        matrix_8_we0,
        matrix_8_d0,
        matrix_9_address0,
        matrix_9_ce0,
        matrix_9_we0,
        matrix_9_d0,
        matrix_10_address0,
        matrix_10_ce0,
        matrix_10_we0,
        matrix_10_d0,
        matrix_11_address0,
        matrix_11_ce0,
        matrix_11_we0,
        matrix_11_d0,
        matrix_12_address0,
        matrix_12_ce0,
        matrix_12_we0,
        matrix_12_d0,
        matrix_13_address0,
        matrix_13_ce0,
        matrix_13_we0,
        matrix_13_d0,
        matrix_14_address0,
        matrix_14_ce0,
        matrix_14_we0,
        matrix_14_d0,
        matrix_15_address0,
        matrix_15_ce0,
        matrix_15_we0,
        matrix_15_d0,
        zero_percentage,
        global_lfsr_seed_V_i,
        global_lfsr_seed_V_o,
        global_lfsr_seed_V_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] matrix_0_address0;
output   matrix_0_ce0;
output   matrix_0_we0;
output  [0:0] matrix_0_d0;
output  [6:0] matrix_1_address0;
output   matrix_1_ce0;
output   matrix_1_we0;
output  [0:0] matrix_1_d0;
output  [6:0] matrix_2_address0;
output   matrix_2_ce0;
output   matrix_2_we0;
output  [0:0] matrix_2_d0;
output  [6:0] matrix_3_address0;
output   matrix_3_ce0;
output   matrix_3_we0;
output  [0:0] matrix_3_d0;
output  [6:0] matrix_4_address0;
output   matrix_4_ce0;
output   matrix_4_we0;
output  [0:0] matrix_4_d0;
output  [6:0] matrix_5_address0;
output   matrix_5_ce0;
output   matrix_5_we0;
output  [0:0] matrix_5_d0;
output  [6:0] matrix_6_address0;
output   matrix_6_ce0;
output   matrix_6_we0;
output  [0:0] matrix_6_d0;
output  [6:0] matrix_7_address0;
output   matrix_7_ce0;
output   matrix_7_we0;
output  [0:0] matrix_7_d0;
output  [6:0] matrix_8_address0;
output   matrix_8_ce0;
output   matrix_8_we0;
output  [0:0] matrix_8_d0;
output  [6:0] matrix_9_address0;
output   matrix_9_ce0;
output   matrix_9_we0;
output  [0:0] matrix_9_d0;
output  [6:0] matrix_10_address0;
output   matrix_10_ce0;
output   matrix_10_we0;
output  [0:0] matrix_10_d0;
output  [6:0] matrix_11_address0;
output   matrix_11_ce0;
output   matrix_11_we0;
output  [0:0] matrix_11_d0;
output  [6:0] matrix_12_address0;
output   matrix_12_ce0;
output   matrix_12_we0;
output  [0:0] matrix_12_d0;
output  [6:0] matrix_13_address0;
output   matrix_13_ce0;
output   matrix_13_we0;
output  [0:0] matrix_13_d0;
output  [6:0] matrix_14_address0;
output   matrix_14_ce0;
output   matrix_14_we0;
output  [0:0] matrix_14_d0;
output  [6:0] matrix_15_address0;
output   matrix_15_ce0;
output   matrix_15_we0;
output  [0:0] matrix_15_d0;
input  [31:0] zero_percentage;
input  [15:0] global_lfsr_seed_V_i;
output  [15:0] global_lfsr_seed_V_o;
output   global_lfsr_seed_V_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg matrix_0_ce0;
reg matrix_0_we0;
reg[0:0] matrix_0_d0;
reg matrix_1_ce0;
reg matrix_1_we0;
reg[0:0] matrix_1_d0;
reg matrix_2_ce0;
reg matrix_2_we0;
reg[0:0] matrix_2_d0;
reg matrix_3_ce0;
reg matrix_3_we0;
reg[0:0] matrix_3_d0;
reg matrix_4_ce0;
reg matrix_4_we0;
reg[0:0] matrix_4_d0;
reg matrix_5_ce0;
reg matrix_5_we0;
reg[0:0] matrix_5_d0;
reg matrix_6_ce0;
reg matrix_6_we0;
reg[0:0] matrix_6_d0;
reg matrix_7_ce0;
reg matrix_7_we0;
reg[0:0] matrix_7_d0;
reg matrix_8_ce0;
reg matrix_8_we0;
reg[0:0] matrix_8_d0;
reg matrix_9_ce0;
reg matrix_9_we0;
reg[0:0] matrix_9_d0;
reg matrix_10_ce0;
reg matrix_10_we0;
reg[0:0] matrix_10_d0;
reg matrix_11_ce0;
reg matrix_11_we0;
reg[0:0] matrix_11_d0;
reg matrix_12_ce0;
reg matrix_12_we0;
reg[0:0] matrix_12_d0;
reg matrix_13_ce0;
reg matrix_13_we0;
reg[0:0] matrix_13_d0;
reg matrix_14_ce0;
reg matrix_14_we0;
reg[0:0] matrix_14_d0;
reg matrix_15_ce0;
reg matrix_15_we0;
reg[0:0] matrix_15_d0;
reg[15:0] global_lfsr_seed_V_o;
reg global_lfsr_seed_V_o_ap_vld;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_569_p2;
reg   [31:0] tmp_reg_2325;
wire    ap_CS_fsm_state4;
reg   [0:0] p_Result_s_reg_2330;
wire    ap_CS_fsm_state8;
wire   [22:0] tmp_V_1_fu_598_p1;
reg   [22:0] tmp_V_1_reg_2335;
wire   [0:0] isNeg_fu_612_p3;
reg   [0:0] isNeg_reg_2340;
wire  signed [8:0] ush_fu_630_p3;
reg  signed [8:0] ush_reg_2345;
wire   [31:0] p_Val2_6_fu_708_p3;
reg   [31:0] p_Val2_6_reg_2351;
wire    ap_CS_fsm_state9;
wire   [6:0] i_fu_725_p2;
reg   [6:0] i_reg_2379;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln96_fu_731_p1;
reg   [63:0] zext_ln96_reg_2384;
wire   [0:0] icmp_ln86_fu_719_p2;
wire   [0:0] tmp_136_fu_757_p3;
reg   [0:0] tmp_136_reg_2402;
wire   [15:0] or_ln68_fu_813_p2;
reg   [15:0] or_ln68_reg_2408;
wire   [0:0] tmp_138_fu_849_p3;
reg   [0:0] tmp_138_reg_2418;
wire   [0:0] tmp_139_fu_857_p3;
reg   [0:0] tmp_139_reg_2423;
wire   [0:0] tmp_140_fu_879_p3;
reg   [0:0] tmp_140_reg_2429;
wire   [15:0] or_ln68_1_fu_913_p2;
reg   [15:0] or_ln68_1_reg_2434;
wire   [31:0] add_ln97_1_fu_942_p2;
wire   [0:0] or_ln94_1_fu_936_p2;
wire   [0:0] tmp_141_fu_954_p3;
reg   [0:0] tmp_141_reg_2451;
wire    ap_CS_fsm_state11;
wire   [15:0] or_ln68_2_fu_1005_p2;
reg   [15:0] or_ln68_2_reg_2457;
wire   [0:0] tmp_143_fu_1041_p3;
reg   [0:0] tmp_143_reg_2467;
wire   [0:0] tmp_144_fu_1063_p3;
reg   [0:0] tmp_144_reg_2473;
wire   [15:0] or_ln68_3_fu_1095_p2;
reg   [15:0] or_ln68_3_reg_2478;
wire   [31:0] add_ln97_3_fu_1124_p2;
wire   [0:0] or_ln94_3_fu_1118_p2;
wire   [15:0] or_ln68_4_fu_1181_p2;
reg   [15:0] or_ln68_4_reg_2495;
wire    ap_CS_fsm_state12;
wire   [15:0] or_ln68_5_fu_1271_p2;
reg   [15:0] or_ln68_5_reg_2505;
wire   [31:0] add_ln97_5_fu_1300_p2;
wire   [0:0] or_ln94_5_fu_1294_p2;
wire   [15:0] or_ln68_6_fu_1353_p2;
reg   [15:0] or_ln68_6_reg_2521;
wire   [15:0] or_ln68_7_fu_1463_p2;
reg   [15:0] or_ln68_7_reg_2533;
wire    ap_CS_fsm_state13;
wire   [31:0] add_ln97_7_fu_1492_p2;
wire   [0:0] or_ln94_7_fu_1486_p2;
wire   [15:0] or_ln68_8_fu_1559_p2;
reg   [15:0] or_ln68_8_reg_2549;
wire   [31:0] add_ln97_9_fu_1698_p2;
wire    ap_CS_fsm_state14;
wire   [0:0] or_ln94_9_fu_1692_p2;
reg   [0:0] tmp_166_reg_2569;
wire   [15:0] or_ln68_10_fu_1773_p2;
reg   [15:0] or_ln68_10_reg_2575;
wire   [31:0] add_ln97_11_fu_1903_p2;
wire    ap_CS_fsm_state15;
wire   [0:0] or_ln94_11_fu_1897_p2;
reg   [0:0] tmp_174_reg_2592;
wire   [15:0] or_ln68_12_fu_1978_p2;
reg   [15:0] or_ln68_12_reg_2598;
wire   [31:0] add_ln97_13_fu_2108_p2;
wire    ap_CS_fsm_state16;
wire   [0:0] or_ln94_13_fu_2102_p2;
reg   [0:0] tmp_182_reg_2615;
wire   [15:0] or_ln68_14_fu_2183_p2;
reg   [15:0] or_ln68_14_reg_2621;
wire   [15:0] or_ln68_15_fu_2284_p2;
wire    ap_CS_fsm_state17;
reg   [15:0] p_090_0_reg_368;
reg   [31:0] zeros_added_0_reg_378;
reg   [31:0] ap_phi_mux_zeros_added_0_be_phi_fu_561_p4;
reg   [6:0] i_0_reg_389;
wire   [31:0] add_ln97_fu_842_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_0_phi_fu_403_p4;
wire   [0:0] or_ln94_fu_836_p2;
reg   [31:0] zeros_added_2_1_reg_411;
wire   [31:0] add_ln97_2_fu_1034_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_2_phi_fu_424_p4;
wire   [0:0] or_ln94_2_fu_1028_p2;
reg   [31:0] zeros_added_2_3_reg_432;
wire   [31:0] add_ln97_4_fu_1210_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_4_phi_fu_445_p4;
wire   [0:0] or_ln94_4_fu_1204_p2;
reg   [31:0] zeros_added_2_5_reg_453;
wire   [31:0] add_ln97_6_fu_1389_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_6_phi_fu_466_p4;
wire   [0:0] or_ln94_6_fu_1383_p2;
reg   [31:0] zeros_added_2_7_reg_474;
wire   [31:0] add_ln97_8_fu_1595_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_8_phi_fu_487_p4;
wire   [0:0] or_ln94_8_fu_1589_p2;
reg   [31:0] zeros_added_2_9_reg_495;
wire   [31:0] add_ln97_10_fu_1801_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_10_phi_fu_508_p4;
wire   [0:0] or_ln94_10_fu_1795_p2;
reg   [31:0] zeros_added_2_11_reg_516;
wire   [31:0] add_ln97_12_fu_2006_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_12_phi_fu_529_p4;
wire   [0:0] or_ln94_12_fu_2000_p2;
reg   [31:0] zeros_added_2_13_reg_537;
wire   [31:0] add_ln97_14_fu_2211_p2;
reg   [31:0] ap_phi_mux_zeros_added_2_14_phi_fu_550_p4;
wire   [0:0] or_ln94_14_fu_2205_p2;
wire   [31:0] add_ln97_15_fu_2313_p2;
wire   [0:0] or_ln94_15_fu_2307_p2;
reg   [31:0] grp_fu_569_p0;
reg   [31:0] grp_fu_569_p1;
wire    ap_CS_fsm_state5;
wire   [31:0] p_Val2_s_fu_576_p1;
wire   [7:0] tmp_V_fu_588_p4;
wire   [8:0] zext_ln339_fu_602_p1;
wire   [8:0] add_ln339_fu_606_p2;
wire   [7:0] sub_ln1311_fu_620_p2;
wire  signed [8:0] sext_ln1311_fu_626_p1;
wire   [24:0] mantissa_V_fu_638_p4;
wire  signed [31:0] sext_ln1311_1_fu_651_p1;
wire  signed [24:0] sext_ln1311_2_fu_654_p1;
wire   [78:0] zext_ln682_fu_647_p1;
wire   [78:0] zext_ln1287_fu_657_p1;
wire   [24:0] r_V_fu_661_p2;
wire   [0:0] tmp_133_fu_673_p3;
wire   [78:0] r_V_1_fu_667_p2;
wire   [31:0] zext_ln662_fu_681_p1;
wire   [31:0] tmp_s_fu_685_p4;
wire   [31:0] p_Val2_5_fu_695_p3;
wire   [31:0] result_V_1_fu_702_p2;
wire   [14:0] trunc_ln3_fu_765_p4;
wire   [0:0] tmp_134_fu_741_p3;
wire   [0:0] trunc_ln91_fu_737_p1;
wire   [0:0] tmp_135_fu_749_p3;
wire   [0:0] xor_ln68_2_fu_793_p2;
wire   [0:0] xor_ln68_1_fu_787_p2;
wire   [0:0] xor_ln68_fu_799_p2;
wire   [15:0] shl_ln_fu_805_p3;
wire  signed [15:0] sext_ln1503_fu_775_p1;
wire   [0:0] icmp_ln94_fu_819_p2;
wire   [0:0] tmp_137_fu_779_p3;
wire   [0:0] xor_ln94_16_fu_824_p2;
wire   [0:0] xor_ln94_fu_830_p2;
wire   [14:0] trunc_ln1503_s_fu_865_p4;
wire   [0:0] xor_ln68_4_fu_893_p2;
wire   [0:0] xor_ln68_3_fu_887_p2;
wire   [0:0] xor_ln68_5_fu_899_p2;
wire   [15:0] shl_ln68_1_fu_905_p3;
wire  signed [15:0] sext_ln1503_1_fu_875_p1;
wire   [0:0] icmp_ln94_1_fu_919_p2;
wire   [0:0] xor_ln94_17_fu_924_p2;
wire   [0:0] xor_ln94_1_fu_930_p2;
wire   [14:0] trunc_ln1503_1_fu_962_p4;
wire   [0:0] xor_ln68_7_fu_986_p2;
wire   [0:0] xor_ln68_6_fu_982_p2;
wire   [0:0] xor_ln68_8_fu_991_p2;
wire   [15:0] shl_ln68_2_fu_997_p3;
wire  signed [15:0] sext_ln1503_2_fu_971_p1;
wire   [0:0] icmp_ln94_2_fu_1011_p2;
wire   [0:0] tmp_142_fu_975_p3;
wire   [0:0] xor_ln94_18_fu_1016_p2;
wire   [0:0] xor_ln94_2_fu_1022_p2;
wire   [14:0] trunc_ln1503_2_fu_1049_p4;
wire   [0:0] xor_ln68_10_fu_1076_p2;
wire   [0:0] xor_ln68_9_fu_1071_p2;
wire   [0:0] xor_ln68_11_fu_1081_p2;
wire   [15:0] shl_ln68_3_fu_1087_p3;
wire  signed [15:0] sext_ln1503_3_fu_1059_p1;
wire   [0:0] icmp_ln94_3_fu_1101_p2;
wire   [0:0] xor_ln94_19_fu_1106_p2;
wire   [0:0] xor_ln94_3_fu_1112_p2;
wire   [14:0] trunc_ln1503_3_fu_1138_p4;
wire   [0:0] tmp_145_fu_1130_p3;
wire   [0:0] xor_ln68_13_fu_1162_p2;
wire   [0:0] xor_ln68_12_fu_1158_p2;
wire   [0:0] xor_ln68_14_fu_1167_p2;
wire   [15:0] shl_ln68_4_fu_1173_p3;
wire  signed [15:0] sext_ln1503_4_fu_1147_p1;
wire   [0:0] icmp_ln94_4_fu_1187_p2;
wire   [0:0] tmp_146_fu_1151_p3;
wire   [0:0] xor_ln94_20_fu_1192_p2;
wire   [0:0] xor_ln94_4_fu_1198_p2;
wire   [14:0] trunc_ln1503_4_fu_1225_p4;
wire   [0:0] tmp_147_fu_1217_p3;
wire   [0:0] xor_ln68_16_fu_1252_p2;
wire   [0:0] xor_ln68_15_fu_1247_p2;
wire   [0:0] xor_ln68_17_fu_1257_p2;
wire   [15:0] shl_ln68_5_fu_1263_p3;
wire  signed [15:0] sext_ln1503_5_fu_1235_p1;
wire   [0:0] icmp_ln94_5_fu_1277_p2;
wire   [0:0] tmp_148_fu_1239_p3;
wire   [0:0] xor_ln94_21_fu_1282_p2;
wire   [0:0] xor_ln94_5_fu_1288_p2;
wire   [14:0] trunc_ln1503_5_fu_1314_p4;
wire   [0:0] tmp_149_fu_1306_p3;
wire   [0:0] xor_ln68_19_fu_1333_p2;
wire   [0:0] xor_ln68_18_fu_1328_p2;
wire   [0:0] xor_ln68_20_fu_1339_p2;
wire   [15:0] shl_ln68_6_fu_1345_p3;
wire  signed [15:0] sext_ln1503_6_fu_1324_p1;
wire   [0:0] icmp_ln94_6_fu_1366_p2;
wire   [0:0] tmp_150_fu_1359_p3;
wire   [0:0] xor_ln94_22_fu_1371_p2;
wire   [0:0] xor_ln94_6_fu_1377_p2;
wire   [14:0] trunc_ln1503_6_fu_1417_p4;
wire   [0:0] tmp_151_fu_1396_p3;
wire   [0:0] tmp_152_fu_1403_p3;
wire   [0:0] tmp_153_fu_1410_p3;
wire   [0:0] xor_ln68_22_fu_1443_p2;
wire   [0:0] xor_ln68_21_fu_1437_p2;
wire   [0:0] xor_ln68_23_fu_1449_p2;
wire   [15:0] shl_ln68_7_fu_1455_p3;
wire  signed [15:0] sext_ln1503_7_fu_1426_p1;
wire   [0:0] icmp_ln94_7_fu_1469_p2;
wire   [0:0] tmp_154_fu_1430_p3;
wire   [0:0] xor_ln94_23_fu_1474_p2;
wire   [0:0] xor_ln94_7_fu_1480_p2;
wire   [14:0] trunc_ln1503_7_fu_1519_p4;
wire   [0:0] tmp_155_fu_1498_p3;
wire   [0:0] tmp_156_fu_1505_p3;
wire   [0:0] tmp_157_fu_1512_p3;
wire   [0:0] xor_ln68_25_fu_1539_p2;
wire   [0:0] xor_ln68_24_fu_1533_p2;
wire   [0:0] xor_ln68_26_fu_1545_p2;
wire   [15:0] shl_ln68_8_fu_1551_p3;
wire  signed [15:0] sext_ln1503_8_fu_1529_p1;
wire   [0:0] icmp_ln94_8_fu_1572_p2;
wire   [0:0] tmp_158_fu_1565_p3;
wire   [0:0] xor_ln94_24_fu_1577_p2;
wire   [0:0] xor_ln94_8_fu_1583_p2;
wire   [14:0] trunc_ln1503_8_fu_1623_p4;
wire   [0:0] tmp_159_fu_1602_p3;
wire   [0:0] tmp_160_fu_1609_p3;
wire   [0:0] tmp_161_fu_1616_p3;
wire   [0:0] xor_ln68_28_fu_1649_p2;
wire   [0:0] xor_ln68_27_fu_1643_p2;
wire   [0:0] xor_ln68_29_fu_1655_p2;
wire   [15:0] shl_ln68_9_fu_1661_p3;
wire  signed [15:0] sext_ln1503_9_fu_1632_p1;
wire   [0:0] icmp_ln94_9_fu_1675_p2;
wire   [0:0] tmp_162_fu_1636_p3;
wire   [0:0] xor_ln94_25_fu_1680_p2;
wire   [0:0] xor_ln94_9_fu_1686_p2;
wire   [15:0] or_ln68_9_fu_1669_p2;
wire   [14:0] trunc_ln1503_9_fu_1725_p4;
wire   [0:0] tmp_163_fu_1704_p3;
wire   [0:0] tmp_164_fu_1711_p3;
wire   [0:0] tmp_165_fu_1718_p3;
wire   [0:0] xor_ln68_31_fu_1753_p2;
wire   [0:0] xor_ln68_30_fu_1747_p2;
wire   [0:0] xor_ln68_32_fu_1759_p2;
wire   [15:0] shl_ln68_s_fu_1765_p3;
wire  signed [15:0] sext_ln1503_10_fu_1735_p1;
wire   [0:0] icmp_ln94_10_fu_1779_p2;
wire   [0:0] xor_ln94_26_fu_1784_p2;
wire   [0:0] xor_ln94_10_fu_1790_p2;
wire   [14:0] trunc_ln1503_10_fu_1829_p4;
wire   [0:0] tmp_167_fu_1808_p3;
wire   [0:0] tmp_168_fu_1815_p3;
wire   [0:0] tmp_169_fu_1822_p3;
wire   [0:0] xor_ln68_34_fu_1854_p2;
wire   [0:0] xor_ln68_33_fu_1849_p2;
wire   [0:0] xor_ln68_35_fu_1860_p2;
wire   [15:0] shl_ln68_10_fu_1866_p3;
wire  signed [15:0] sext_ln1503_11_fu_1838_p1;
wire   [0:0] icmp_ln94_11_fu_1880_p2;
wire   [0:0] tmp_170_fu_1842_p3;
wire   [0:0] xor_ln94_27_fu_1885_p2;
wire   [0:0] xor_ln94_11_fu_1891_p2;
wire   [15:0] or_ln68_11_fu_1874_p2;
wire   [14:0] trunc_ln1503_11_fu_1930_p4;
wire   [0:0] tmp_171_fu_1909_p3;
wire   [0:0] tmp_172_fu_1916_p3;
wire   [0:0] tmp_173_fu_1923_p3;
wire   [0:0] xor_ln68_37_fu_1958_p2;
wire   [0:0] xor_ln68_36_fu_1952_p2;
wire   [0:0] xor_ln68_38_fu_1964_p2;
wire   [15:0] shl_ln68_11_fu_1970_p3;
wire  signed [15:0] sext_ln1503_12_fu_1940_p1;
wire   [0:0] icmp_ln94_12_fu_1984_p2;
wire   [0:0] xor_ln94_28_fu_1989_p2;
wire   [0:0] xor_ln94_12_fu_1995_p2;
wire   [14:0] trunc_ln1503_12_fu_2034_p4;
wire   [0:0] tmp_175_fu_2013_p3;
wire   [0:0] tmp_176_fu_2020_p3;
wire   [0:0] tmp_177_fu_2027_p3;
wire   [0:0] xor_ln68_40_fu_2059_p2;
wire   [0:0] xor_ln68_39_fu_2054_p2;
wire   [0:0] xor_ln68_41_fu_2065_p2;
wire   [15:0] shl_ln68_12_fu_2071_p3;
wire  signed [15:0] sext_ln1503_13_fu_2043_p1;
wire   [0:0] icmp_ln94_13_fu_2085_p2;
wire   [0:0] tmp_178_fu_2047_p3;
wire   [0:0] xor_ln94_29_fu_2090_p2;
wire   [0:0] xor_ln94_13_fu_2096_p2;
wire   [15:0] or_ln68_13_fu_2079_p2;
wire   [14:0] trunc_ln1503_13_fu_2135_p4;
wire   [0:0] tmp_179_fu_2114_p3;
wire   [0:0] tmp_180_fu_2121_p3;
wire   [0:0] tmp_181_fu_2128_p3;
wire   [0:0] xor_ln68_43_fu_2163_p2;
wire   [0:0] xor_ln68_42_fu_2157_p2;
wire   [0:0] xor_ln68_44_fu_2169_p2;
wire   [15:0] shl_ln68_13_fu_2175_p3;
wire  signed [15:0] sext_ln1503_14_fu_2145_p1;
wire   [0:0] icmp_ln94_14_fu_2189_p2;
wire   [0:0] xor_ln94_30_fu_2194_p2;
wire   [0:0] xor_ln94_14_fu_2200_p2;
wire   [14:0] trunc_ln1503_14_fu_2239_p4;
wire   [0:0] tmp_183_fu_2218_p3;
wire   [0:0] tmp_184_fu_2225_p3;
wire   [0:0] tmp_185_fu_2232_p3;
wire   [0:0] xor_ln68_46_fu_2264_p2;
wire   [0:0] xor_ln68_45_fu_2259_p2;
wire   [0:0] xor_ln68_47_fu_2270_p2;
wire   [15:0] shl_ln68_14_fu_2276_p3;
wire  signed [15:0] sext_ln1503_15_fu_2248_p1;
wire   [0:0] icmp_ln94_15_fu_2290_p2;
wire   [0:0] tmp_186_fu_2252_p3;
wire   [0:0] xor_ln94_31_fu_2295_p2;
wire   [0:0] xor_ln94_15_fu_2301_p2;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
end

dut_fmul_32ns_32nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fmul_32ns_32nbkb_U99(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_569_p0),
    .din1(grp_fu_569_p1),
    .ce(1'b1),
    .dout(grp_fu_569_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        i_0_reg_389 <= i_reg_2379;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_0_reg_389 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        p_090_0_reg_368 <= or_ln68_15_fu_2284_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        p_090_0_reg_368 <= global_lfsr_seed_V_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        zeros_added_0_reg_378 <= ap_phi_mux_zeros_added_0_be_phi_fu_561_p4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        zeros_added_0_reg_378 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        if ((or_ln94_11_fu_1897_p2 == 1'd1)) begin
            zeros_added_2_11_reg_516 <= ap_phi_mux_zeros_added_2_10_phi_fu_508_p4;
        end else if ((or_ln94_11_fu_1897_p2 == 1'd0)) begin
            zeros_added_2_11_reg_516 <= add_ln97_11_fu_1903_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((or_ln94_13_fu_2102_p2 == 1'd1)) begin
            zeros_added_2_13_reg_537 <= ap_phi_mux_zeros_added_2_12_phi_fu_529_p4;
        end else if ((or_ln94_13_fu_2102_p2 == 1'd0)) begin
            zeros_added_2_13_reg_537 <= add_ln97_13_fu_2108_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0))) begin
        if ((or_ln94_1_fu_936_p2 == 1'd1)) begin
            zeros_added_2_1_reg_411 <= ap_phi_mux_zeros_added_2_0_phi_fu_403_p4;
        end else if ((or_ln94_1_fu_936_p2 == 1'd0)) begin
            zeros_added_2_1_reg_411 <= add_ln97_1_fu_942_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((or_ln94_3_fu_1118_p2 == 1'd1)) begin
            zeros_added_2_3_reg_432 <= ap_phi_mux_zeros_added_2_2_phi_fu_424_p4;
        end else if ((or_ln94_3_fu_1118_p2 == 1'd0)) begin
            zeros_added_2_3_reg_432 <= add_ln97_3_fu_1124_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        if ((or_ln94_5_fu_1294_p2 == 1'd1)) begin
            zeros_added_2_5_reg_453 <= ap_phi_mux_zeros_added_2_4_phi_fu_445_p4;
        end else if ((or_ln94_5_fu_1294_p2 == 1'd0)) begin
            zeros_added_2_5_reg_453 <= add_ln97_5_fu_1300_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((or_ln94_7_fu_1486_p2 == 1'd1)) begin
            zeros_added_2_7_reg_474 <= ap_phi_mux_zeros_added_2_6_phi_fu_466_p4;
        end else if ((or_ln94_7_fu_1486_p2 == 1'd0)) begin
            zeros_added_2_7_reg_474 <= add_ln97_7_fu_1492_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        if ((or_ln94_9_fu_1692_p2 == 1'd1)) begin
            zeros_added_2_9_reg_495 <= ap_phi_mux_zeros_added_2_8_phi_fu_487_p4;
        end else if ((or_ln94_9_fu_1692_p2 == 1'd0)) begin
            zeros_added_2_9_reg_495 <= add_ln97_9_fu_1698_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_reg_2379 <= i_fu_725_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        isNeg_reg_2340 <= add_ln339_fu_606_p2[32'd8];
        p_Result_s_reg_2330 <= p_Val2_s_fu_576_p1[32'd31];
        tmp_V_1_reg_2335 <= tmp_V_1_fu_598_p1;
        ush_reg_2345 <= ush_fu_630_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        or_ln68_10_reg_2575 <= or_ln68_10_fu_1773_p2;
        tmp_166_reg_2569 <= or_ln68_9_fu_1669_p2[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        or_ln68_12_reg_2598 <= or_ln68_12_fu_1978_p2;
        tmp_174_reg_2592 <= or_ln68_11_fu_1874_p2[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        or_ln68_14_reg_2621 <= or_ln68_14_fu_2183_p2;
        tmp_182_reg_2615 <= or_ln68_13_fu_2079_p2[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0))) begin
        or_ln68_1_reg_2434 <= or_ln68_1_fu_913_p2;
        or_ln68_reg_2408 <= or_ln68_fu_813_p2;
        tmp_136_reg_2402 <= p_090_0_reg_368[32'd5];
        tmp_138_reg_2418 <= p_090_0_reg_368[32'd4];
        tmp_139_reg_2423 <= p_090_0_reg_368[32'd6];
        tmp_140_reg_2429 <= or_ln68_fu_813_p2[32'd1];
        zext_ln96_reg_2384[6 : 0] <= zext_ln96_fu_731_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        or_ln68_2_reg_2457 <= or_ln68_2_fu_1005_p2;
        or_ln68_3_reg_2478 <= or_ln68_3_fu_1095_p2;
        tmp_141_reg_2451 <= p_090_0_reg_368[32'd7];
        tmp_143_reg_2467 <= p_090_0_reg_368[32'd8];
        tmp_144_reg_2473 <= or_ln68_2_fu_1005_p2[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        or_ln68_4_reg_2495 <= or_ln68_4_fu_1181_p2;
        or_ln68_5_reg_2505 <= or_ln68_5_fu_1271_p2;
        or_ln68_6_reg_2521 <= or_ln68_6_fu_1353_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        or_ln68_7_reg_2533 <= or_ln68_7_fu_1463_p2;
        or_ln68_8_reg_2549 <= or_ln68_8_fu_1559_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_Val2_6_reg_2351 <= p_Val2_6_fu_708_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_reg_2325 <= grp_fu_569_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        if ((or_ln94_15_fu_2307_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 = ap_phi_mux_zeros_added_2_14_phi_fu_550_p4;
        end else if ((or_ln94_15_fu_2307_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 = add_ln97_15_fu_2313_p2;
        end else begin
            ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0))) begin
        if ((or_ln94_fu_836_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 = zeros_added_0_reg_378;
        end else if ((or_ln94_fu_836_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 = add_ln97_fu_842_p2;
        end else begin
            ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        if ((or_ln94_10_fu_1795_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 = zeros_added_2_9_reg_495;
        end else if ((or_ln94_10_fu_1795_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 = add_ln97_10_fu_1801_p2;
        end else begin
            ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((or_ln94_12_fu_2000_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 = zeros_added_2_11_reg_516;
        end else if ((or_ln94_12_fu_2000_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 = add_ln97_12_fu_2006_p2;
        end else begin
            ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        if ((or_ln94_14_fu_2205_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 = zeros_added_2_13_reg_537;
        end else if ((or_ln94_14_fu_2205_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 = add_ln97_14_fu_2211_p2;
        end else begin
            ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((or_ln94_2_fu_1028_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 = zeros_added_2_1_reg_411;
        end else if ((or_ln94_2_fu_1028_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 = add_ln97_2_fu_1034_p2;
        end else begin
            ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        if ((or_ln94_4_fu_1204_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 = zeros_added_2_3_reg_432;
        end else if ((or_ln94_4_fu_1204_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 = add_ln97_4_fu_1210_p2;
        end else begin
            ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((or_ln94_6_fu_1383_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 = zeros_added_2_5_reg_453;
        end else if ((or_ln94_6_fu_1383_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 = add_ln97_6_fu_1389_p2;
        end else begin
            ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        if ((or_ln94_8_fu_1589_p2 == 1'd1)) begin
            ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 = zeros_added_2_7_reg_474;
        end else if ((or_ln94_8_fu_1589_p2 == 1'd0)) begin
            ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 = add_ln97_8_fu_1595_p2;
        end else begin
            ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd1))) begin
        global_lfsr_seed_V_o = p_090_0_reg_368;
    end else begin
        global_lfsr_seed_V_o = global_lfsr_seed_V_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd1))) begin
        global_lfsr_seed_V_o_ap_vld = 1'b1;
    end else begin
        global_lfsr_seed_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_569_p0 = tmp_reg_2325;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_569_p0 = zero_percentage;
    end else begin
        grp_fu_569_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_569_p1 = 32'd1098907648;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_569_p1 = 32'd1120403456;
    end else begin
        grp_fu_569_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_fu_836_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state10) & (or_ln94_fu_836_p2 == 1'd0) & (icmp_ln86_fu_719_p2 == 1'd0)))) begin
        matrix_0_ce0 = 1'b1;
    end else begin
        matrix_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0))) begin
        if ((or_ln94_fu_836_p2 == 1'd1)) begin
            matrix_0_d0 = 1'd1;
        end else if ((or_ln94_fu_836_p2 == 1'd0)) begin
            matrix_0_d0 = 1'd0;
        end else begin
            matrix_0_d0 = 'bx;
        end
    end else begin
        matrix_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_fu_836_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state10) & (or_ln94_fu_836_p2 == 1'd0) & (icmp_ln86_fu_719_p2 == 1'd0)))) begin
        matrix_0_we0 = 1'b1;
    end else begin
        matrix_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_10_fu_1795_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((1'b1 == ap_CS_fsm_state15) & (or_ln94_10_fu_1795_p2 == 1'd0)))) begin
        matrix_10_ce0 = 1'b1;
    end else begin
        matrix_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        if ((or_ln94_10_fu_1795_p2 == 1'd1)) begin
            matrix_10_d0 = 1'd1;
        end else if ((or_ln94_10_fu_1795_p2 == 1'd0)) begin
            matrix_10_d0 = 1'd0;
        end else begin
            matrix_10_d0 = 'bx;
        end
    end else begin
        matrix_10_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_10_fu_1795_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((1'b1 == ap_CS_fsm_state15) & (or_ln94_10_fu_1795_p2 == 1'd0)))) begin
        matrix_10_we0 = 1'b1;
    end else begin
        matrix_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_11_fu_1897_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((1'b1 == ap_CS_fsm_state15) & (or_ln94_11_fu_1897_p2 == 1'd0)))) begin
        matrix_11_ce0 = 1'b1;
    end else begin
        matrix_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        if ((or_ln94_11_fu_1897_p2 == 1'd1)) begin
            matrix_11_d0 = 1'd1;
        end else if ((or_ln94_11_fu_1897_p2 == 1'd0)) begin
            matrix_11_d0 = 1'd0;
        end else begin
            matrix_11_d0 = 'bx;
        end
    end else begin
        matrix_11_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_11_fu_1897_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((1'b1 == ap_CS_fsm_state15) & (or_ln94_11_fu_1897_p2 == 1'd0)))) begin
        matrix_11_we0 = 1'b1;
    end else begin
        matrix_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_12_fu_2000_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state16) & (or_ln94_12_fu_2000_p2 == 1'd0)))) begin
        matrix_12_ce0 = 1'b1;
    end else begin
        matrix_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((or_ln94_12_fu_2000_p2 == 1'd1)) begin
            matrix_12_d0 = 1'd1;
        end else if ((or_ln94_12_fu_2000_p2 == 1'd0)) begin
            matrix_12_d0 = 1'd0;
        end else begin
            matrix_12_d0 = 'bx;
        end
    end else begin
        matrix_12_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_12_fu_2000_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state16) & (or_ln94_12_fu_2000_p2 == 1'd0)))) begin
        matrix_12_we0 = 1'b1;
    end else begin
        matrix_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_13_fu_2102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state16) & (or_ln94_13_fu_2102_p2 == 1'd0)))) begin
        matrix_13_ce0 = 1'b1;
    end else begin
        matrix_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((or_ln94_13_fu_2102_p2 == 1'd1)) begin
            matrix_13_d0 = 1'd1;
        end else if ((or_ln94_13_fu_2102_p2 == 1'd0)) begin
            matrix_13_d0 = 1'd0;
        end else begin
            matrix_13_d0 = 'bx;
        end
    end else begin
        matrix_13_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_13_fu_2102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state16) & (or_ln94_13_fu_2102_p2 == 1'd0)))) begin
        matrix_13_we0 = 1'b1;
    end else begin
        matrix_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_14_fu_2205_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17)) | ((1'b1 == ap_CS_fsm_state17) & (or_ln94_14_fu_2205_p2 == 1'd0)))) begin
        matrix_14_ce0 = 1'b1;
    end else begin
        matrix_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        if ((or_ln94_14_fu_2205_p2 == 1'd1)) begin
            matrix_14_d0 = 1'd1;
        end else if ((or_ln94_14_fu_2205_p2 == 1'd0)) begin
            matrix_14_d0 = 1'd0;
        end else begin
            matrix_14_d0 = 'bx;
        end
    end else begin
        matrix_14_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_14_fu_2205_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17)) | ((1'b1 == ap_CS_fsm_state17) & (or_ln94_14_fu_2205_p2 == 1'd0)))) begin
        matrix_14_we0 = 1'b1;
    end else begin
        matrix_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_15_fu_2307_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17)) | ((1'b1 == ap_CS_fsm_state17) & (or_ln94_15_fu_2307_p2 == 1'd0)))) begin
        matrix_15_ce0 = 1'b1;
    end else begin
        matrix_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        if ((or_ln94_15_fu_2307_p2 == 1'd1)) begin
            matrix_15_d0 = 1'd1;
        end else if ((or_ln94_15_fu_2307_p2 == 1'd0)) begin
            matrix_15_d0 = 1'd0;
        end else begin
            matrix_15_d0 = 'bx;
        end
    end else begin
        matrix_15_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_15_fu_2307_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17)) | ((1'b1 == ap_CS_fsm_state17) & (or_ln94_15_fu_2307_p2 == 1'd0)))) begin
        matrix_15_we0 = 1'b1;
    end else begin
        matrix_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_1_fu_936_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state10) & (or_ln94_1_fu_936_p2 == 1'd0) & (icmp_ln86_fu_719_p2 == 1'd0)))) begin
        matrix_1_ce0 = 1'b1;
    end else begin
        matrix_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0))) begin
        if ((or_ln94_1_fu_936_p2 == 1'd1)) begin
            matrix_1_d0 = 1'd1;
        end else if ((or_ln94_1_fu_936_p2 == 1'd0)) begin
            matrix_1_d0 = 1'd0;
        end else begin
            matrix_1_d0 = 'bx;
        end
    end else begin
        matrix_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_1_fu_936_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state10) & (or_ln94_1_fu_936_p2 == 1'd0) & (icmp_ln86_fu_719_p2 == 1'd0)))) begin
        matrix_1_we0 = 1'b1;
    end else begin
        matrix_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_2_fu_1028_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state11) & (or_ln94_2_fu_1028_p2 == 1'd0)))) begin
        matrix_2_ce0 = 1'b1;
    end else begin
        matrix_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((or_ln94_2_fu_1028_p2 == 1'd1)) begin
            matrix_2_d0 = 1'd1;
        end else if ((or_ln94_2_fu_1028_p2 == 1'd0)) begin
            matrix_2_d0 = 1'd0;
        end else begin
            matrix_2_d0 = 'bx;
        end
    end else begin
        matrix_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_2_fu_1028_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state11) & (or_ln94_2_fu_1028_p2 == 1'd0)))) begin
        matrix_2_we0 = 1'b1;
    end else begin
        matrix_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_3_fu_1118_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state11) & (or_ln94_3_fu_1118_p2 == 1'd0)))) begin
        matrix_3_ce0 = 1'b1;
    end else begin
        matrix_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((or_ln94_3_fu_1118_p2 == 1'd1)) begin
            matrix_3_d0 = 1'd1;
        end else if ((or_ln94_3_fu_1118_p2 == 1'd0)) begin
            matrix_3_d0 = 1'd0;
        end else begin
            matrix_3_d0 = 'bx;
        end
    end else begin
        matrix_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_3_fu_1118_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state11) & (or_ln94_3_fu_1118_p2 == 1'd0)))) begin
        matrix_3_we0 = 1'b1;
    end else begin
        matrix_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_4_fu_1204_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state12) & (or_ln94_4_fu_1204_p2 == 1'd0)))) begin
        matrix_4_ce0 = 1'b1;
    end else begin
        matrix_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        if ((or_ln94_4_fu_1204_p2 == 1'd1)) begin
            matrix_4_d0 = 1'd1;
        end else if ((or_ln94_4_fu_1204_p2 == 1'd0)) begin
            matrix_4_d0 = 1'd0;
        end else begin
            matrix_4_d0 = 'bx;
        end
    end else begin
        matrix_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_4_fu_1204_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state12) & (or_ln94_4_fu_1204_p2 == 1'd0)))) begin
        matrix_4_we0 = 1'b1;
    end else begin
        matrix_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_5_fu_1294_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state12) & (or_ln94_5_fu_1294_p2 == 1'd0)))) begin
        matrix_5_ce0 = 1'b1;
    end else begin
        matrix_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        if ((or_ln94_5_fu_1294_p2 == 1'd1)) begin
            matrix_5_d0 = 1'd1;
        end else if ((or_ln94_5_fu_1294_p2 == 1'd0)) begin
            matrix_5_d0 = 1'd0;
        end else begin
            matrix_5_d0 = 'bx;
        end
    end else begin
        matrix_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_5_fu_1294_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state12) & (or_ln94_5_fu_1294_p2 == 1'd0)))) begin
        matrix_5_we0 = 1'b1;
    end else begin
        matrix_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_6_fu_1383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13)) | ((1'b1 == ap_CS_fsm_state13) & (or_ln94_6_fu_1383_p2 == 1'd0)))) begin
        matrix_6_ce0 = 1'b1;
    end else begin
        matrix_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((or_ln94_6_fu_1383_p2 == 1'd1)) begin
            matrix_6_d0 = 1'd1;
        end else if ((or_ln94_6_fu_1383_p2 == 1'd0)) begin
            matrix_6_d0 = 1'd0;
        end else begin
            matrix_6_d0 = 'bx;
        end
    end else begin
        matrix_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_6_fu_1383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13)) | ((1'b1 == ap_CS_fsm_state13) & (or_ln94_6_fu_1383_p2 == 1'd0)))) begin
        matrix_6_we0 = 1'b1;
    end else begin
        matrix_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_7_fu_1486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13)) | ((1'b1 == ap_CS_fsm_state13) & (or_ln94_7_fu_1486_p2 == 1'd0)))) begin
        matrix_7_ce0 = 1'b1;
    end else begin
        matrix_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((or_ln94_7_fu_1486_p2 == 1'd1)) begin
            matrix_7_d0 = 1'd1;
        end else if ((or_ln94_7_fu_1486_p2 == 1'd0)) begin
            matrix_7_d0 = 1'd0;
        end else begin
            matrix_7_d0 = 'bx;
        end
    end else begin
        matrix_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_7_fu_1486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13)) | ((1'b1 == ap_CS_fsm_state13) & (or_ln94_7_fu_1486_p2 == 1'd0)))) begin
        matrix_7_we0 = 1'b1;
    end else begin
        matrix_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_8_fu_1589_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == ap_CS_fsm_state14) & (or_ln94_8_fu_1589_p2 == 1'd0)))) begin
        matrix_8_ce0 = 1'b1;
    end else begin
        matrix_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        if ((or_ln94_8_fu_1589_p2 == 1'd1)) begin
            matrix_8_d0 = 1'd1;
        end else if ((or_ln94_8_fu_1589_p2 == 1'd0)) begin
            matrix_8_d0 = 1'd0;
        end else begin
            matrix_8_d0 = 'bx;
        end
    end else begin
        matrix_8_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_8_fu_1589_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == ap_CS_fsm_state14) & (or_ln94_8_fu_1589_p2 == 1'd0)))) begin
        matrix_8_we0 = 1'b1;
    end else begin
        matrix_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln94_9_fu_1692_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == ap_CS_fsm_state14) & (or_ln94_9_fu_1692_p2 == 1'd0)))) begin
        matrix_9_ce0 = 1'b1;
    end else begin
        matrix_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        if ((or_ln94_9_fu_1692_p2 == 1'd1)) begin
            matrix_9_d0 = 1'd1;
        end else if ((or_ln94_9_fu_1692_p2 == 1'd0)) begin
            matrix_9_d0 = 1'd0;
        end else begin
            matrix_9_d0 = 'bx;
        end
    end else begin
        matrix_9_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((or_ln94_9_fu_1692_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == ap_CS_fsm_state14) & (or_ln94_9_fu_1692_p2 == 1'd0)))) begin
        matrix_9_we0 = 1'b1;
    end else begin
        matrix_9_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln86_fu_719_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln339_fu_606_p2 = ($signed(9'd385) + $signed(zext_ln339_fu_602_p1));

assign add_ln97_10_fu_1801_p2 = (zeros_added_2_9_reg_495 + 32'd1);

assign add_ln97_11_fu_1903_p2 = (ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 + 32'd1);

assign add_ln97_12_fu_2006_p2 = (zeros_added_2_11_reg_516 + 32'd1);

assign add_ln97_13_fu_2108_p2 = (ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 + 32'd1);

assign add_ln97_14_fu_2211_p2 = (zeros_added_2_13_reg_537 + 32'd1);

assign add_ln97_15_fu_2313_p2 = (ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 + 32'd1);

assign add_ln97_1_fu_942_p2 = (ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 + 32'd1);

assign add_ln97_2_fu_1034_p2 = (zeros_added_2_1_reg_411 + 32'd1);

assign add_ln97_3_fu_1124_p2 = (ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 + 32'd1);

assign add_ln97_4_fu_1210_p2 = (zeros_added_2_3_reg_432 + 32'd1);

assign add_ln97_5_fu_1300_p2 = (ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 + 32'd1);

assign add_ln97_6_fu_1389_p2 = (zeros_added_2_5_reg_453 + 32'd1);

assign add_ln97_7_fu_1492_p2 = (ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 + 32'd1);

assign add_ln97_8_fu_1595_p2 = (zeros_added_2_7_reg_474 + 32'd1);

assign add_ln97_9_fu_1698_p2 = (ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 + 32'd1);

assign add_ln97_fu_842_p2 = (zeros_added_0_reg_378 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign i_fu_725_p2 = (i_0_reg_389 + 7'd1);

assign icmp_ln86_fu_719_p2 = ((i_0_reg_389 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln94_10_fu_1779_p2 = (($signed(zeros_added_2_9_reg_495) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_11_fu_1880_p2 = (($signed(ap_phi_mux_zeros_added_2_10_phi_fu_508_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_12_fu_1984_p2 = (($signed(zeros_added_2_11_reg_516) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_13_fu_2085_p2 = (($signed(ap_phi_mux_zeros_added_2_12_phi_fu_529_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_14_fu_2189_p2 = (($signed(zeros_added_2_13_reg_537) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_15_fu_2290_p2 = (($signed(ap_phi_mux_zeros_added_2_14_phi_fu_550_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_1_fu_919_p2 = (($signed(ap_phi_mux_zeros_added_2_0_phi_fu_403_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_2_fu_1011_p2 = (($signed(zeros_added_2_1_reg_411) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_3_fu_1101_p2 = (($signed(ap_phi_mux_zeros_added_2_2_phi_fu_424_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_4_fu_1187_p2 = (($signed(zeros_added_2_3_reg_432) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_5_fu_1277_p2 = (($signed(ap_phi_mux_zeros_added_2_4_phi_fu_445_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_6_fu_1366_p2 = (($signed(zeros_added_2_5_reg_453) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_7_fu_1469_p2 = (($signed(ap_phi_mux_zeros_added_2_6_phi_fu_466_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_8_fu_1572_p2 = (($signed(zeros_added_2_7_reg_474) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_9_fu_1675_p2 = (($signed(ap_phi_mux_zeros_added_2_8_phi_fu_487_p4) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_819_p2 = (($signed(zeros_added_0_reg_378) < $signed(p_Val2_6_reg_2351)) ? 1'b1 : 1'b0);

assign isNeg_fu_612_p3 = add_ln339_fu_606_p2[32'd8];

assign mantissa_V_fu_638_p4 = {{{{1'd1}, {tmp_V_1_reg_2335}}}, {1'd0}};

assign matrix_0_address0 = zext_ln96_fu_731_p1;

assign matrix_10_address0 = zext_ln96_reg_2384;

assign matrix_11_address0 = zext_ln96_reg_2384;

assign matrix_12_address0 = zext_ln96_reg_2384;

assign matrix_13_address0 = zext_ln96_reg_2384;

assign matrix_14_address0 = zext_ln96_reg_2384;

assign matrix_15_address0 = zext_ln96_reg_2384;

assign matrix_1_address0 = zext_ln96_fu_731_p1;

assign matrix_2_address0 = zext_ln96_reg_2384;

assign matrix_3_address0 = zext_ln96_reg_2384;

assign matrix_4_address0 = zext_ln96_reg_2384;

assign matrix_5_address0 = zext_ln96_reg_2384;

assign matrix_6_address0 = zext_ln96_reg_2384;

assign matrix_7_address0 = zext_ln96_reg_2384;

assign matrix_8_address0 = zext_ln96_reg_2384;

assign matrix_9_address0 = zext_ln96_reg_2384;

assign or_ln68_10_fu_1773_p2 = (shl_ln68_s_fu_1765_p3 | sext_ln1503_10_fu_1735_p1);

assign or_ln68_11_fu_1874_p2 = (shl_ln68_10_fu_1866_p3 | sext_ln1503_11_fu_1838_p1);

assign or_ln68_12_fu_1978_p2 = (shl_ln68_11_fu_1970_p3 | sext_ln1503_12_fu_1940_p1);

assign or_ln68_13_fu_2079_p2 = (shl_ln68_12_fu_2071_p3 | sext_ln1503_13_fu_2043_p1);

assign or_ln68_14_fu_2183_p2 = (shl_ln68_13_fu_2175_p3 | sext_ln1503_14_fu_2145_p1);

assign or_ln68_15_fu_2284_p2 = (shl_ln68_14_fu_2276_p3 | sext_ln1503_15_fu_2248_p1);

assign or_ln68_1_fu_913_p2 = (shl_ln68_1_fu_905_p3 | sext_ln1503_1_fu_875_p1);

assign or_ln68_2_fu_1005_p2 = (shl_ln68_2_fu_997_p3 | sext_ln1503_2_fu_971_p1);

assign or_ln68_3_fu_1095_p2 = (shl_ln68_3_fu_1087_p3 | sext_ln1503_3_fu_1059_p1);

assign or_ln68_4_fu_1181_p2 = (shl_ln68_4_fu_1173_p3 | sext_ln1503_4_fu_1147_p1);

assign or_ln68_5_fu_1271_p2 = (shl_ln68_5_fu_1263_p3 | sext_ln1503_5_fu_1235_p1);

assign or_ln68_6_fu_1353_p2 = (shl_ln68_6_fu_1345_p3 | sext_ln1503_6_fu_1324_p1);

assign or_ln68_7_fu_1463_p2 = (shl_ln68_7_fu_1455_p3 | sext_ln1503_7_fu_1426_p1);

assign or_ln68_8_fu_1559_p2 = (shl_ln68_8_fu_1551_p3 | sext_ln1503_8_fu_1529_p1);

assign or_ln68_9_fu_1669_p2 = (shl_ln68_9_fu_1661_p3 | sext_ln1503_9_fu_1632_p1);

assign or_ln68_fu_813_p2 = (shl_ln_fu_805_p3 | sext_ln1503_fu_775_p1);

assign or_ln94_10_fu_1795_p2 = (xor_ln94_26_fu_1784_p2 | xor_ln94_10_fu_1790_p2);

assign or_ln94_11_fu_1897_p2 = (xor_ln94_27_fu_1885_p2 | xor_ln94_11_fu_1891_p2);

assign or_ln94_12_fu_2000_p2 = (xor_ln94_28_fu_1989_p2 | xor_ln94_12_fu_1995_p2);

assign or_ln94_13_fu_2102_p2 = (xor_ln94_29_fu_2090_p2 | xor_ln94_13_fu_2096_p2);

assign or_ln94_14_fu_2205_p2 = (xor_ln94_30_fu_2194_p2 | xor_ln94_14_fu_2200_p2);

assign or_ln94_15_fu_2307_p2 = (xor_ln94_31_fu_2295_p2 | xor_ln94_15_fu_2301_p2);

assign or_ln94_1_fu_936_p2 = (xor_ln94_1_fu_930_p2 | xor_ln94_17_fu_924_p2);

assign or_ln94_2_fu_1028_p2 = (xor_ln94_2_fu_1022_p2 | xor_ln94_18_fu_1016_p2);

assign or_ln94_3_fu_1118_p2 = (xor_ln94_3_fu_1112_p2 | xor_ln94_19_fu_1106_p2);

assign or_ln94_4_fu_1204_p2 = (xor_ln94_4_fu_1198_p2 | xor_ln94_20_fu_1192_p2);

assign or_ln94_5_fu_1294_p2 = (xor_ln94_5_fu_1288_p2 | xor_ln94_21_fu_1282_p2);

assign or_ln94_6_fu_1383_p2 = (xor_ln94_6_fu_1377_p2 | xor_ln94_22_fu_1371_p2);

assign or_ln94_7_fu_1486_p2 = (xor_ln94_7_fu_1480_p2 | xor_ln94_23_fu_1474_p2);

assign or_ln94_8_fu_1589_p2 = (xor_ln94_8_fu_1583_p2 | xor_ln94_24_fu_1577_p2);

assign or_ln94_9_fu_1692_p2 = (xor_ln94_9_fu_1686_p2 | xor_ln94_25_fu_1680_p2);

assign or_ln94_fu_836_p2 = (xor_ln94_fu_830_p2 | xor_ln94_16_fu_824_p2);

assign p_Val2_5_fu_695_p3 = ((isNeg_reg_2340[0:0] === 1'b1) ? zext_ln662_fu_681_p1 : tmp_s_fu_685_p4);

assign p_Val2_6_fu_708_p3 = ((p_Result_s_reg_2330[0:0] === 1'b1) ? result_V_1_fu_702_p2 : p_Val2_5_fu_695_p3);

assign p_Val2_s_fu_576_p1 = grp_fu_569_p2;

assign r_V_1_fu_667_p2 = zext_ln682_fu_647_p1 << zext_ln1287_fu_657_p1;

assign r_V_fu_661_p2 = mantissa_V_fu_638_p4 >> sext_ln1311_2_fu_654_p1;

assign result_V_1_fu_702_p2 = (32'd0 - p_Val2_5_fu_695_p3);

assign sext_ln1311_1_fu_651_p1 = ush_reg_2345;

assign sext_ln1311_2_fu_654_p1 = ush_reg_2345;

assign sext_ln1311_fu_626_p1 = $signed(sub_ln1311_fu_620_p2);

assign sext_ln1503_10_fu_1735_p1 = $signed(trunc_ln1503_9_fu_1725_p4);

assign sext_ln1503_11_fu_1838_p1 = $signed(trunc_ln1503_10_fu_1829_p4);

assign sext_ln1503_12_fu_1940_p1 = $signed(trunc_ln1503_11_fu_1930_p4);

assign sext_ln1503_13_fu_2043_p1 = $signed(trunc_ln1503_12_fu_2034_p4);

assign sext_ln1503_14_fu_2145_p1 = $signed(trunc_ln1503_13_fu_2135_p4);

assign sext_ln1503_15_fu_2248_p1 = $signed(trunc_ln1503_14_fu_2239_p4);

assign sext_ln1503_1_fu_875_p1 = $signed(trunc_ln1503_s_fu_865_p4);

assign sext_ln1503_2_fu_971_p1 = $signed(trunc_ln1503_1_fu_962_p4);

assign sext_ln1503_3_fu_1059_p1 = $signed(trunc_ln1503_2_fu_1049_p4);

assign sext_ln1503_4_fu_1147_p1 = $signed(trunc_ln1503_3_fu_1138_p4);

assign sext_ln1503_5_fu_1235_p1 = $signed(trunc_ln1503_4_fu_1225_p4);

assign sext_ln1503_6_fu_1324_p1 = $signed(trunc_ln1503_5_fu_1314_p4);

assign sext_ln1503_7_fu_1426_p1 = $signed(trunc_ln1503_6_fu_1417_p4);

assign sext_ln1503_8_fu_1529_p1 = $signed(trunc_ln1503_7_fu_1519_p4);

assign sext_ln1503_9_fu_1632_p1 = $signed(trunc_ln1503_8_fu_1623_p4);

assign sext_ln1503_fu_775_p1 = $signed(trunc_ln3_fu_765_p4);

assign shl_ln68_10_fu_1866_p3 = {{xor_ln68_35_fu_1860_p2}, {15'd0}};

assign shl_ln68_11_fu_1970_p3 = {{xor_ln68_38_fu_1964_p2}, {15'd0}};

assign shl_ln68_12_fu_2071_p3 = {{xor_ln68_41_fu_2065_p2}, {15'd0}};

assign shl_ln68_13_fu_2175_p3 = {{xor_ln68_44_fu_2169_p2}, {15'd0}};

assign shl_ln68_14_fu_2276_p3 = {{xor_ln68_47_fu_2270_p2}, {15'd0}};

assign shl_ln68_1_fu_905_p3 = {{xor_ln68_5_fu_899_p2}, {15'd0}};

assign shl_ln68_2_fu_997_p3 = {{xor_ln68_8_fu_991_p2}, {15'd0}};

assign shl_ln68_3_fu_1087_p3 = {{xor_ln68_11_fu_1081_p2}, {15'd0}};

assign shl_ln68_4_fu_1173_p3 = {{xor_ln68_14_fu_1167_p2}, {15'd0}};

assign shl_ln68_5_fu_1263_p3 = {{xor_ln68_17_fu_1257_p2}, {15'd0}};

assign shl_ln68_6_fu_1345_p3 = {{xor_ln68_20_fu_1339_p2}, {15'd0}};

assign shl_ln68_7_fu_1455_p3 = {{xor_ln68_23_fu_1449_p2}, {15'd0}};

assign shl_ln68_8_fu_1551_p3 = {{xor_ln68_26_fu_1545_p2}, {15'd0}};

assign shl_ln68_9_fu_1661_p3 = {{xor_ln68_29_fu_1655_p2}, {15'd0}};

assign shl_ln68_s_fu_1765_p3 = {{xor_ln68_32_fu_1759_p2}, {15'd0}};

assign shl_ln_fu_805_p3 = {{xor_ln68_fu_799_p2}, {15'd0}};

assign sub_ln1311_fu_620_p2 = (8'd127 - tmp_V_fu_588_p4);

assign tmp_133_fu_673_p3 = r_V_fu_661_p2[32'd24];

assign tmp_134_fu_741_p3 = p_090_0_reg_368[32'd2];

assign tmp_135_fu_749_p3 = p_090_0_reg_368[32'd3];

assign tmp_136_fu_757_p3 = p_090_0_reg_368[32'd5];

assign tmp_137_fu_779_p3 = p_090_0_reg_368[32'd1];

assign tmp_138_fu_849_p3 = p_090_0_reg_368[32'd4];

assign tmp_139_fu_857_p3 = p_090_0_reg_368[32'd6];

assign tmp_140_fu_879_p3 = or_ln68_fu_813_p2[32'd1];

assign tmp_141_fu_954_p3 = p_090_0_reg_368[32'd7];

assign tmp_142_fu_975_p3 = or_ln68_1_reg_2434[32'd1];

assign tmp_143_fu_1041_p3 = p_090_0_reg_368[32'd8];

assign tmp_144_fu_1063_p3 = or_ln68_2_fu_1005_p2[32'd1];

assign tmp_145_fu_1130_p3 = p_090_0_reg_368[32'd9];

assign tmp_146_fu_1151_p3 = or_ln68_3_reg_2478[32'd1];

assign tmp_147_fu_1217_p3 = p_090_0_reg_368[32'd10];

assign tmp_148_fu_1239_p3 = or_ln68_4_fu_1181_p2[32'd1];

assign tmp_149_fu_1306_p3 = p_090_0_reg_368[32'd11];

assign tmp_150_fu_1359_p3 = or_ln68_5_reg_2505[32'd1];

assign tmp_151_fu_1396_p3 = or_ln68_reg_2408[32'd8];

assign tmp_152_fu_1403_p3 = or_ln68_reg_2408[32'd9];

assign tmp_153_fu_1410_p3 = or_ln68_reg_2408[32'd11];

assign tmp_154_fu_1430_p3 = or_ln68_6_reg_2521[32'd1];

assign tmp_155_fu_1498_p3 = or_ln68_1_reg_2434[32'd8];

assign tmp_156_fu_1505_p3 = or_ln68_1_reg_2434[32'd9];

assign tmp_157_fu_1512_p3 = or_ln68_1_reg_2434[32'd11];

assign tmp_158_fu_1565_p3 = or_ln68_7_reg_2533[32'd1];

assign tmp_159_fu_1602_p3 = or_ln68_2_reg_2457[32'd8];

assign tmp_160_fu_1609_p3 = or_ln68_2_reg_2457[32'd9];

assign tmp_161_fu_1616_p3 = or_ln68_2_reg_2457[32'd11];

assign tmp_162_fu_1636_p3 = or_ln68_8_reg_2549[32'd1];

assign tmp_163_fu_1704_p3 = or_ln68_3_reg_2478[32'd8];

assign tmp_164_fu_1711_p3 = or_ln68_3_reg_2478[32'd9];

assign tmp_165_fu_1718_p3 = or_ln68_3_reg_2478[32'd11];

assign tmp_167_fu_1808_p3 = or_ln68_4_reg_2495[32'd8];

assign tmp_168_fu_1815_p3 = or_ln68_4_reg_2495[32'd9];

assign tmp_169_fu_1822_p3 = or_ln68_4_reg_2495[32'd11];

assign tmp_170_fu_1842_p3 = or_ln68_10_reg_2575[32'd1];

assign tmp_171_fu_1909_p3 = or_ln68_5_reg_2505[32'd8];

assign tmp_172_fu_1916_p3 = or_ln68_5_reg_2505[32'd9];

assign tmp_173_fu_1923_p3 = or_ln68_5_reg_2505[32'd11];

assign tmp_175_fu_2013_p3 = or_ln68_6_reg_2521[32'd8];

assign tmp_176_fu_2020_p3 = or_ln68_6_reg_2521[32'd9];

assign tmp_177_fu_2027_p3 = or_ln68_6_reg_2521[32'd11];

assign tmp_178_fu_2047_p3 = or_ln68_12_reg_2598[32'd1];

assign tmp_179_fu_2114_p3 = or_ln68_7_reg_2533[32'd8];

assign tmp_180_fu_2121_p3 = or_ln68_7_reg_2533[32'd9];

assign tmp_181_fu_2128_p3 = or_ln68_7_reg_2533[32'd11];

assign tmp_183_fu_2218_p3 = or_ln68_8_reg_2549[32'd8];

assign tmp_184_fu_2225_p3 = or_ln68_8_reg_2549[32'd9];

assign tmp_185_fu_2232_p3 = or_ln68_8_reg_2549[32'd11];

assign tmp_186_fu_2252_p3 = or_ln68_14_reg_2621[32'd1];

assign tmp_V_1_fu_598_p1 = p_Val2_s_fu_576_p1[22:0];

assign tmp_V_fu_588_p4 = {{p_Val2_s_fu_576_p1[30:23]}};

assign tmp_s_fu_685_p4 = {{r_V_1_fu_667_p2[55:24]}};

assign trunc_ln1503_10_fu_1829_p4 = {{or_ln68_10_reg_2575[15:1]}};

assign trunc_ln1503_11_fu_1930_p4 = {{or_ln68_11_fu_1874_p2[15:1]}};

assign trunc_ln1503_12_fu_2034_p4 = {{or_ln68_12_reg_2598[15:1]}};

assign trunc_ln1503_13_fu_2135_p4 = {{or_ln68_13_fu_2079_p2[15:1]}};

assign trunc_ln1503_14_fu_2239_p4 = {{or_ln68_14_reg_2621[15:1]}};

assign trunc_ln1503_1_fu_962_p4 = {{or_ln68_1_reg_2434[15:1]}};

assign trunc_ln1503_2_fu_1049_p4 = {{or_ln68_2_fu_1005_p2[15:1]}};

assign trunc_ln1503_3_fu_1138_p4 = {{or_ln68_3_reg_2478[15:1]}};

assign trunc_ln1503_4_fu_1225_p4 = {{or_ln68_4_fu_1181_p2[15:1]}};

assign trunc_ln1503_5_fu_1314_p4 = {{or_ln68_5_fu_1271_p2[15:1]}};

assign trunc_ln1503_6_fu_1417_p4 = {{or_ln68_6_reg_2521[15:1]}};

assign trunc_ln1503_7_fu_1519_p4 = {{or_ln68_7_fu_1463_p2[15:1]}};

assign trunc_ln1503_8_fu_1623_p4 = {{or_ln68_8_reg_2549[15:1]}};

assign trunc_ln1503_9_fu_1725_p4 = {{or_ln68_9_fu_1669_p2[15:1]}};

assign trunc_ln1503_s_fu_865_p4 = {{or_ln68_fu_813_p2[15:1]}};

assign trunc_ln3_fu_765_p4 = {{p_090_0_reg_368[15:1]}};

assign trunc_ln91_fu_737_p1 = p_090_0_reg_368[0:0];

assign ush_fu_630_p3 = ((isNeg_fu_612_p3[0:0] === 1'b1) ? sext_ln1311_fu_626_p1 : add_ln339_fu_606_p2);

assign xor_ln68_10_fu_1076_p2 = (tmp_143_fu_1041_p3 ^ tmp_139_reg_2423);

assign xor_ln68_11_fu_1081_p2 = (xor_ln68_9_fu_1071_p2 ^ xor_ln68_10_fu_1076_p2);

assign xor_ln68_12_fu_1158_p2 = (tmp_144_reg_2473 ^ tmp_139_reg_2423);

assign xor_ln68_13_fu_1162_p2 = (tmp_145_fu_1130_p3 ^ tmp_141_reg_2451);

assign xor_ln68_14_fu_1167_p2 = (xor_ln68_13_fu_1162_p2 ^ xor_ln68_12_fu_1158_p2);

assign xor_ln68_15_fu_1247_p2 = (tmp_146_fu_1151_p3 ^ tmp_141_reg_2451);

assign xor_ln68_16_fu_1252_p2 = (tmp_147_fu_1217_p3 ^ tmp_143_reg_2467);

assign xor_ln68_17_fu_1257_p2 = (xor_ln68_16_fu_1252_p2 ^ xor_ln68_15_fu_1247_p2);

assign xor_ln68_18_fu_1328_p2 = (tmp_148_fu_1239_p3 ^ tmp_143_reg_2467);

assign xor_ln68_19_fu_1333_p2 = (tmp_149_fu_1306_p3 ^ tmp_145_fu_1130_p3);

assign xor_ln68_1_fu_787_p2 = (trunc_ln91_fu_737_p1 ^ tmp_134_fu_741_p3);

assign xor_ln68_20_fu_1339_p2 = (xor_ln68_19_fu_1333_p2 ^ xor_ln68_18_fu_1328_p2);

assign xor_ln68_21_fu_1437_p2 = (tmp_151_fu_1396_p3 ^ tmp_150_fu_1359_p3);

assign xor_ln68_22_fu_1443_p2 = (tmp_153_fu_1410_p3 ^ tmp_152_fu_1403_p3);

assign xor_ln68_23_fu_1449_p2 = (xor_ln68_22_fu_1443_p2 ^ xor_ln68_21_fu_1437_p2);

assign xor_ln68_24_fu_1533_p2 = (tmp_155_fu_1498_p3 ^ tmp_154_fu_1430_p3);

assign xor_ln68_25_fu_1539_p2 = (tmp_157_fu_1512_p3 ^ tmp_156_fu_1505_p3);

assign xor_ln68_26_fu_1545_p2 = (xor_ln68_25_fu_1539_p2 ^ xor_ln68_24_fu_1533_p2);

assign xor_ln68_27_fu_1643_p2 = (tmp_159_fu_1602_p3 ^ tmp_158_fu_1565_p3);

assign xor_ln68_28_fu_1649_p2 = (tmp_161_fu_1616_p3 ^ tmp_160_fu_1609_p3);

assign xor_ln68_29_fu_1655_p2 = (xor_ln68_28_fu_1649_p2 ^ xor_ln68_27_fu_1643_p2);

assign xor_ln68_2_fu_793_p2 = (tmp_136_fu_757_p3 ^ tmp_135_fu_749_p3);

assign xor_ln68_30_fu_1747_p2 = (tmp_163_fu_1704_p3 ^ tmp_162_fu_1636_p3);

assign xor_ln68_31_fu_1753_p2 = (tmp_165_fu_1718_p3 ^ tmp_164_fu_1711_p3);

assign xor_ln68_32_fu_1759_p2 = (xor_ln68_31_fu_1753_p2 ^ xor_ln68_30_fu_1747_p2);

assign xor_ln68_33_fu_1849_p2 = (tmp_167_fu_1808_p3 ^ tmp_166_reg_2569);

assign xor_ln68_34_fu_1854_p2 = (tmp_169_fu_1822_p3 ^ tmp_168_fu_1815_p3);

assign xor_ln68_35_fu_1860_p2 = (xor_ln68_34_fu_1854_p2 ^ xor_ln68_33_fu_1849_p2);

assign xor_ln68_36_fu_1952_p2 = (tmp_171_fu_1909_p3 ^ tmp_170_fu_1842_p3);

assign xor_ln68_37_fu_1958_p2 = (tmp_173_fu_1923_p3 ^ tmp_172_fu_1916_p3);

assign xor_ln68_38_fu_1964_p2 = (xor_ln68_37_fu_1958_p2 ^ xor_ln68_36_fu_1952_p2);

assign xor_ln68_39_fu_2054_p2 = (tmp_175_fu_2013_p3 ^ tmp_174_reg_2592);

assign xor_ln68_3_fu_887_p2 = (tmp_137_fu_779_p3 ^ tmp_135_fu_749_p3);

assign xor_ln68_40_fu_2059_p2 = (tmp_177_fu_2027_p3 ^ tmp_176_fu_2020_p3);

assign xor_ln68_41_fu_2065_p2 = (xor_ln68_40_fu_2059_p2 ^ xor_ln68_39_fu_2054_p2);

assign xor_ln68_42_fu_2157_p2 = (tmp_179_fu_2114_p3 ^ tmp_178_fu_2047_p3);

assign xor_ln68_43_fu_2163_p2 = (tmp_181_fu_2128_p3 ^ tmp_180_fu_2121_p3);

assign xor_ln68_44_fu_2169_p2 = (xor_ln68_43_fu_2163_p2 ^ xor_ln68_42_fu_2157_p2);

assign xor_ln68_45_fu_2259_p2 = (tmp_183_fu_2218_p3 ^ tmp_182_reg_2615);

assign xor_ln68_46_fu_2264_p2 = (tmp_185_fu_2232_p3 ^ tmp_184_fu_2225_p3);

assign xor_ln68_47_fu_2270_p2 = (xor_ln68_46_fu_2264_p2 ^ xor_ln68_45_fu_2259_p2);

assign xor_ln68_4_fu_893_p2 = (tmp_139_fu_857_p3 ^ tmp_138_fu_849_p3);

assign xor_ln68_5_fu_899_p2 = (xor_ln68_4_fu_893_p2 ^ xor_ln68_3_fu_887_p2);

assign xor_ln68_6_fu_982_p2 = (tmp_140_reg_2429 ^ tmp_138_reg_2418);

assign xor_ln68_7_fu_986_p2 = (tmp_141_fu_954_p3 ^ tmp_136_reg_2402);

assign xor_ln68_8_fu_991_p2 = (xor_ln68_7_fu_986_p2 ^ xor_ln68_6_fu_982_p2);

assign xor_ln68_9_fu_1071_p2 = (tmp_142_fu_975_p3 ^ tmp_136_reg_2402);

assign xor_ln68_fu_799_p2 = (xor_ln68_2_fu_793_p2 ^ xor_ln68_1_fu_787_p2);

assign xor_ln94_10_fu_1790_p2 = (tmp_166_reg_2569 ^ 1'd1);

assign xor_ln94_11_fu_1891_p2 = (tmp_170_fu_1842_p3 ^ 1'd1);

assign xor_ln94_12_fu_1995_p2 = (tmp_174_reg_2592 ^ 1'd1);

assign xor_ln94_13_fu_2096_p2 = (tmp_178_fu_2047_p3 ^ 1'd1);

assign xor_ln94_14_fu_2200_p2 = (tmp_182_reg_2615 ^ 1'd1);

assign xor_ln94_15_fu_2301_p2 = (tmp_186_fu_2252_p3 ^ 1'd1);

assign xor_ln94_16_fu_824_p2 = (icmp_ln94_fu_819_p2 ^ 1'd1);

assign xor_ln94_17_fu_924_p2 = (icmp_ln94_1_fu_919_p2 ^ 1'd1);

assign xor_ln94_18_fu_1016_p2 = (icmp_ln94_2_fu_1011_p2 ^ 1'd1);

assign xor_ln94_19_fu_1106_p2 = (icmp_ln94_3_fu_1101_p2 ^ 1'd1);

assign xor_ln94_1_fu_930_p2 = (tmp_140_fu_879_p3 ^ 1'd1);

assign xor_ln94_20_fu_1192_p2 = (icmp_ln94_4_fu_1187_p2 ^ 1'd1);

assign xor_ln94_21_fu_1282_p2 = (icmp_ln94_5_fu_1277_p2 ^ 1'd1);

assign xor_ln94_22_fu_1371_p2 = (icmp_ln94_6_fu_1366_p2 ^ 1'd1);

assign xor_ln94_23_fu_1474_p2 = (icmp_ln94_7_fu_1469_p2 ^ 1'd1);

assign xor_ln94_24_fu_1577_p2 = (icmp_ln94_8_fu_1572_p2 ^ 1'd1);

assign xor_ln94_25_fu_1680_p2 = (icmp_ln94_9_fu_1675_p2 ^ 1'd1);

assign xor_ln94_26_fu_1784_p2 = (icmp_ln94_10_fu_1779_p2 ^ 1'd1);

assign xor_ln94_27_fu_1885_p2 = (icmp_ln94_11_fu_1880_p2 ^ 1'd1);

assign xor_ln94_28_fu_1989_p2 = (icmp_ln94_12_fu_1984_p2 ^ 1'd1);

assign xor_ln94_29_fu_2090_p2 = (icmp_ln94_13_fu_2085_p2 ^ 1'd1);

assign xor_ln94_2_fu_1022_p2 = (tmp_142_fu_975_p3 ^ 1'd1);

assign xor_ln94_30_fu_2194_p2 = (icmp_ln94_14_fu_2189_p2 ^ 1'd1);

assign xor_ln94_31_fu_2295_p2 = (icmp_ln94_15_fu_2290_p2 ^ 1'd1);

assign xor_ln94_3_fu_1112_p2 = (tmp_144_fu_1063_p3 ^ 1'd1);

assign xor_ln94_4_fu_1198_p2 = (tmp_146_fu_1151_p3 ^ 1'd1);

assign xor_ln94_5_fu_1288_p2 = (tmp_148_fu_1239_p3 ^ 1'd1);

assign xor_ln94_6_fu_1377_p2 = (tmp_150_fu_1359_p3 ^ 1'd1);

assign xor_ln94_7_fu_1480_p2 = (tmp_154_fu_1430_p3 ^ 1'd1);

assign xor_ln94_8_fu_1583_p2 = (tmp_158_fu_1565_p3 ^ 1'd1);

assign xor_ln94_9_fu_1686_p2 = (tmp_162_fu_1636_p3 ^ 1'd1);

assign xor_ln94_fu_830_p2 = (tmp_137_fu_779_p3 ^ 1'd1);

assign zext_ln1287_fu_657_p1 = $unsigned(sext_ln1311_1_fu_651_p1);

assign zext_ln339_fu_602_p1 = tmp_V_fu_588_p4;

assign zext_ln662_fu_681_p1 = tmp_133_fu_673_p3;

assign zext_ln682_fu_647_p1 = mantissa_V_fu_638_p4;

assign zext_ln96_fu_731_p1 = i_0_reg_389;

always @ (posedge ap_clk) begin
    zext_ln96_reg_2384[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //generate_binary_matr_2
