-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity generate_binary_matr_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    matrix_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_0_ce0 : OUT STD_LOGIC;
    matrix_0_we0 : OUT STD_LOGIC;
    matrix_0_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_1_ce0 : OUT STD_LOGIC;
    matrix_1_we0 : OUT STD_LOGIC;
    matrix_1_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_2_ce0 : OUT STD_LOGIC;
    matrix_2_we0 : OUT STD_LOGIC;
    matrix_2_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_3_ce0 : OUT STD_LOGIC;
    matrix_3_we0 : OUT STD_LOGIC;
    matrix_3_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_4_ce0 : OUT STD_LOGIC;
    matrix_4_we0 : OUT STD_LOGIC;
    matrix_4_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_5_ce0 : OUT STD_LOGIC;
    matrix_5_we0 : OUT STD_LOGIC;
    matrix_5_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_6_ce0 : OUT STD_LOGIC;
    matrix_6_we0 : OUT STD_LOGIC;
    matrix_6_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_7_ce0 : OUT STD_LOGIC;
    matrix_7_we0 : OUT STD_LOGIC;
    matrix_7_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_8_ce0 : OUT STD_LOGIC;
    matrix_8_we0 : OUT STD_LOGIC;
    matrix_8_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_9_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_9_ce0 : OUT STD_LOGIC;
    matrix_9_we0 : OUT STD_LOGIC;
    matrix_9_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_10_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_10_ce0 : OUT STD_LOGIC;
    matrix_10_we0 : OUT STD_LOGIC;
    matrix_10_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_11_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_11_ce0 : OUT STD_LOGIC;
    matrix_11_we0 : OUT STD_LOGIC;
    matrix_11_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_12_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_12_ce0 : OUT STD_LOGIC;
    matrix_12_we0 : OUT STD_LOGIC;
    matrix_12_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_13_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_13_ce0 : OUT STD_LOGIC;
    matrix_13_we0 : OUT STD_LOGIC;
    matrix_13_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_14_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_14_ce0 : OUT STD_LOGIC;
    matrix_14_we0 : OUT STD_LOGIC;
    matrix_14_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    matrix_15_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    matrix_15_ce0 : OUT STD_LOGIC;
    matrix_15_we0 : OUT STD_LOGIC;
    matrix_15_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    zero_percentage : IN STD_LOGIC_VECTOR (31 downto 0);
    global_lfsr_seed_V_i : IN STD_LOGIC_VECTOR (15 downto 0);
    global_lfsr_seed_V_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    global_lfsr_seed_V_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of generate_binary_matr_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_42C80000 : STD_LOGIC_VECTOR (31 downto 0) := "01000010110010000000000000000000";
    constant ap_const_lv32_41800000 : STD_LOGIC_VECTOR (31 downto 0) := "01000001100000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv7_64 : STD_LOGIC_VECTOR (6 downto 0) := "1100100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_569_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_2325 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_Result_s_reg_2330 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_V_1_fu_598_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_V_1_reg_2335 : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_fu_612_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_2340 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_fu_630_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_reg_2345 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_6_fu_708_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_6_reg_2351 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal i_fu_725_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_reg_2379 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal zext_ln96_fu_731_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln96_reg_2384 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln86_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_136_fu_757_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_136_reg_2402 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_fu_813_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_reg_2408 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_138_fu_849_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_138_reg_2418 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_fu_857_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_reg_2423 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_fu_879_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_reg_2429 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_1_fu_913_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_1_reg_2434 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_1_fu_942_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_1_fu_936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_141_fu_954_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_141_reg_2451 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal or_ln68_2_fu_1005_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_2_reg_2457 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_143_fu_1041_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_143_reg_2467 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_144_fu_1063_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_144_reg_2473 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_3_fu_1095_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_3_reg_2478 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_3_fu_1124_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_3_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_4_fu_1181_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_4_reg_2495 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal or_ln68_5_fu_1271_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_5_reg_2505 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_5_fu_1300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_5_fu_1294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_6_fu_1353_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_6_reg_2521 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_7_fu_1463_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_7_reg_2533 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal add_ln97_7_fu_1492_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_7_fu_1486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_8_fu_1559_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_8_reg_2549 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_9_fu_1698_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal or_ln94_9_fu_1692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_166_reg_2569 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_10_fu_1773_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_10_reg_2575 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_11_fu_1903_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal or_ln94_11_fu_1897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_174_reg_2592 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_12_fu_1978_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_12_reg_2598 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_13_fu_2108_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal or_ln94_13_fu_2102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_182_reg_2615 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_14_fu_2183_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_14_reg_2621 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln68_15_fu_2284_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal p_090_0_reg_368 : STD_LOGIC_VECTOR (15 downto 0);
    signal zeros_added_0_reg_378 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_389 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln97_fu_842_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_1_reg_411 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_2_fu_1034_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_2_fu_1028_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_3_reg_432 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_4_fu_1210_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_4_fu_1204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_5_reg_453 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_6_fu_1389_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_6_fu_1383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_7_reg_474 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_8_fu_1595_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_8_fu_1589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_9_reg_495 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_10_fu_1801_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_10_fu_1795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_11_reg_516 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_12_fu_2006_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_12_fu_2000_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zeros_added_2_13_reg_537 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln97_14_fu_2211_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_14_fu_2205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln97_15_fu_2313_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln94_15_fu_2307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_569_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_569_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_Val2_s_fu_576_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_fu_588_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln339_fu_602_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln339_fu_606_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1311_fu_620_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1311_fu_626_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_V_fu_638_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1311_1_fu_651_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1311_2_fu_654_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln682_fu_647_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln1287_fu_657_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_fu_661_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_133_fu_673_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_667_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln662_fu_681_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_685_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_5_fu_695_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_1_fu_702_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln3_fu_765_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_134_fu_741_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln91_fu_737_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_135_fu_749_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_2_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_1_fu_787_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_805_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_fu_775_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_137_fu_779_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_16_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_s_fu_865_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln68_4_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_3_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_5_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_1_fu_905_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_1_fu_875_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_1_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_17_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_1_fu_930_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_1_fu_962_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln68_7_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_6_fu_982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_8_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_2_fu_997_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_2_fu_971_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_2_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_142_fu_975_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_18_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_2_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_2_fu_1049_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln68_10_fu_1076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_9_fu_1071_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_11_fu_1081_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_3_fu_1087_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_3_fu_1059_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_3_fu_1101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_19_fu_1106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_3_fu_1112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_3_fu_1138_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_145_fu_1130_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_13_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_12_fu_1158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_14_fu_1167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_4_fu_1173_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_4_fu_1147_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_4_fu_1187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_146_fu_1151_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_20_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_4_fu_1198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_4_fu_1225_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_147_fu_1217_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_16_fu_1252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_15_fu_1247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_17_fu_1257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_5_fu_1263_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_5_fu_1235_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_5_fu_1277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_fu_1239_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_21_fu_1282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_5_fu_1288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_5_fu_1314_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_149_fu_1306_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_19_fu_1333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_18_fu_1328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_20_fu_1339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_6_fu_1345_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_6_fu_1324_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_6_fu_1366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_150_fu_1359_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_22_fu_1371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_6_fu_1377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_6_fu_1417_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_151_fu_1396_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_152_fu_1403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_153_fu_1410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_22_fu_1443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_21_fu_1437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_23_fu_1449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_7_fu_1455_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_7_fu_1426_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_7_fu_1469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_154_fu_1430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_23_fu_1474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_7_fu_1480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_7_fu_1519_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_155_fu_1498_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_156_fu_1505_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_157_fu_1512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_25_fu_1539_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_24_fu_1533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_26_fu_1545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_8_fu_1551_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_8_fu_1529_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_8_fu_1572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_158_fu_1565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_24_fu_1577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_8_fu_1583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_8_fu_1623_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_159_fu_1602_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_160_fu_1609_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_161_fu_1616_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_28_fu_1649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_27_fu_1643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_29_fu_1655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_9_fu_1661_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_9_fu_1632_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_9_fu_1675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_162_fu_1636_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_25_fu_1680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_9_fu_1686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_9_fu_1669_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1503_9_fu_1725_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_163_fu_1704_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_164_fu_1711_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_165_fu_1718_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_31_fu_1753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_30_fu_1747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_32_fu_1759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_s_fu_1765_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_10_fu_1735_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_10_fu_1779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_26_fu_1784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_10_fu_1790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_10_fu_1829_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_167_fu_1808_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_168_fu_1815_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_169_fu_1822_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_34_fu_1854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_33_fu_1849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_35_fu_1860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_10_fu_1866_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_11_fu_1838_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_11_fu_1880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_170_fu_1842_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_27_fu_1885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_11_fu_1891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_11_fu_1874_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1503_11_fu_1930_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_171_fu_1909_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_172_fu_1916_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_173_fu_1923_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_37_fu_1958_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_36_fu_1952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_38_fu_1964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_11_fu_1970_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_12_fu_1940_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_12_fu_1984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_28_fu_1989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_12_fu_1995_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_12_fu_2034_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_175_fu_2013_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_176_fu_2020_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_177_fu_2027_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_40_fu_2059_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_39_fu_2054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_41_fu_2065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_12_fu_2071_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_13_fu_2043_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_13_fu_2085_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_178_fu_2047_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_29_fu_2090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_13_fu_2096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_13_fu_2079_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1503_13_fu_2135_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_179_fu_2114_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_180_fu_2121_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_181_fu_2128_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_43_fu_2163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_42_fu_2157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_44_fu_2169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_13_fu_2175_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_14_fu_2145_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_14_fu_2189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_30_fu_2194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_14_fu_2200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1503_14_fu_2239_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_183_fu_2218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_184_fu_2225_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_185_fu_2232_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_46_fu_2264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_45_fu_2259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_47_fu_2270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln68_14_fu_2276_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1503_15_fu_2248_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln94_15_fu_2290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_186_fu_2252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_31_fu_2295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln94_15_fu_2301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);

    component dut_fmul_32ns_32nbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    dut_fmul_32ns_32nbkb_U99 : component dut_fmul_32ns_32nbkb
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_569_p0,
        din1 => grp_fu_569_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_569_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_389_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                i_0_reg_389 <= i_reg_2379;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                i_0_reg_389 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    p_090_0_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                p_090_0_reg_368 <= or_ln68_15_fu_2284_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                p_090_0_reg_368 <= global_lfsr_seed_V_i;
            end if; 
        end if;
    end process;

    zeros_added_0_reg_378_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                zeros_added_0_reg_378 <= ap_phi_mux_zeros_added_0_be_phi_fu_561_p4;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                zeros_added_0_reg_378 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    zeros_added_2_11_reg_516_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                if ((or_ln94_11_fu_1897_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_11_reg_516 <= ap_phi_mux_zeros_added_2_10_phi_fu_508_p4;
                elsif ((or_ln94_11_fu_1897_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_11_reg_516 <= add_ln97_11_fu_1903_p2;
                end if;
            end if; 
        end if;
    end process;

    zeros_added_2_13_reg_537_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                if ((or_ln94_13_fu_2102_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_13_reg_537 <= ap_phi_mux_zeros_added_2_12_phi_fu_529_p4;
                elsif ((or_ln94_13_fu_2102_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_13_reg_537 <= add_ln97_13_fu_2108_p2;
                end if;
            end if; 
        end if;
    end process;

    zeros_added_2_1_reg_411_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0))) then
                if ((or_ln94_1_fu_936_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_1_reg_411 <= ap_phi_mux_zeros_added_2_0_phi_fu_403_p4;
                elsif ((or_ln94_1_fu_936_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_1_reg_411 <= add_ln97_1_fu_942_p2;
                end if;
            end if; 
        end if;
    end process;

    zeros_added_2_3_reg_432_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                if ((or_ln94_3_fu_1118_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_3_reg_432 <= ap_phi_mux_zeros_added_2_2_phi_fu_424_p4;
                elsif ((or_ln94_3_fu_1118_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_3_reg_432 <= add_ln97_3_fu_1124_p2;
                end if;
            end if; 
        end if;
    end process;

    zeros_added_2_5_reg_453_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                if ((or_ln94_5_fu_1294_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_5_reg_453 <= ap_phi_mux_zeros_added_2_4_phi_fu_445_p4;
                elsif ((or_ln94_5_fu_1294_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_5_reg_453 <= add_ln97_5_fu_1300_p2;
                end if;
            end if; 
        end if;
    end process;

    zeros_added_2_7_reg_474_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                if ((or_ln94_7_fu_1486_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_7_reg_474 <= ap_phi_mux_zeros_added_2_6_phi_fu_466_p4;
                elsif ((or_ln94_7_fu_1486_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_7_reg_474 <= add_ln97_7_fu_1492_p2;
                end if;
            end if; 
        end if;
    end process;

    zeros_added_2_9_reg_495_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                if ((or_ln94_9_fu_1692_p2 = ap_const_lv1_1)) then 
                    zeros_added_2_9_reg_495 <= ap_phi_mux_zeros_added_2_8_phi_fu_487_p4;
                elsif ((or_ln94_9_fu_1692_p2 = ap_const_lv1_0)) then 
                    zeros_added_2_9_reg_495 <= add_ln97_9_fu_1698_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                i_reg_2379 <= i_fu_725_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                isNeg_reg_2340 <= add_ln339_fu_606_p2(8 downto 8);
                p_Result_s_reg_2330 <= p_Val2_s_fu_576_p1(31 downto 31);
                tmp_V_1_reg_2335 <= tmp_V_1_fu_598_p1;
                ush_reg_2345 <= ush_fu_630_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                or_ln68_10_reg_2575 <= or_ln68_10_fu_1773_p2;
                tmp_166_reg_2569 <= or_ln68_9_fu_1669_p2(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                or_ln68_12_reg_2598 <= or_ln68_12_fu_1978_p2;
                tmp_174_reg_2592 <= or_ln68_11_fu_1874_p2(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                or_ln68_14_reg_2621 <= or_ln68_14_fu_2183_p2;
                tmp_182_reg_2615 <= or_ln68_13_fu_2079_p2(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0))) then
                or_ln68_1_reg_2434 <= or_ln68_1_fu_913_p2;
                or_ln68_reg_2408 <= or_ln68_fu_813_p2;
                tmp_136_reg_2402 <= p_090_0_reg_368(5 downto 5);
                tmp_138_reg_2418 <= p_090_0_reg_368(4 downto 4);
                tmp_139_reg_2423 <= p_090_0_reg_368(6 downto 6);
                tmp_140_reg_2429 <= or_ln68_fu_813_p2(1 downto 1);
                    zext_ln96_reg_2384(6 downto 0) <= zext_ln96_fu_731_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                or_ln68_2_reg_2457 <= or_ln68_2_fu_1005_p2;
                or_ln68_3_reg_2478 <= or_ln68_3_fu_1095_p2;
                tmp_141_reg_2451 <= p_090_0_reg_368(7 downto 7);
                tmp_143_reg_2467 <= p_090_0_reg_368(8 downto 8);
                tmp_144_reg_2473 <= or_ln68_2_fu_1005_p2(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                or_ln68_4_reg_2495 <= or_ln68_4_fu_1181_p2;
                or_ln68_5_reg_2505 <= or_ln68_5_fu_1271_p2;
                or_ln68_6_reg_2521 <= or_ln68_6_fu_1353_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                or_ln68_7_reg_2533 <= or_ln68_7_fu_1463_p2;
                or_ln68_8_reg_2549 <= or_ln68_8_fu_1559_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                p_Val2_6_reg_2351 <= p_Val2_6_fu_708_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_reg_2325 <= grp_fu_569_p2;
            end if;
        end if;
    end process;
    zext_ln96_reg_2384(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state10, icmp_ln86_fu_719_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln339_fu_606_p2 <= std_logic_vector(signed(ap_const_lv9_181) + signed(zext_ln339_fu_602_p1));
    add_ln97_10_fu_1801_p2 <= std_logic_vector(unsigned(zeros_added_2_9_reg_495) + unsigned(ap_const_lv32_1));
    add_ln97_11_fu_1903_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_10_phi_fu_508_p4) + unsigned(ap_const_lv32_1));
    add_ln97_12_fu_2006_p2 <= std_logic_vector(unsigned(zeros_added_2_11_reg_516) + unsigned(ap_const_lv32_1));
    add_ln97_13_fu_2108_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_12_phi_fu_529_p4) + unsigned(ap_const_lv32_1));
    add_ln97_14_fu_2211_p2 <= std_logic_vector(unsigned(zeros_added_2_13_reg_537) + unsigned(ap_const_lv32_1));
    add_ln97_15_fu_2313_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_14_phi_fu_550_p4) + unsigned(ap_const_lv32_1));
    add_ln97_1_fu_942_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_0_phi_fu_403_p4) + unsigned(ap_const_lv32_1));
    add_ln97_2_fu_1034_p2 <= std_logic_vector(unsigned(zeros_added_2_1_reg_411) + unsigned(ap_const_lv32_1));
    add_ln97_3_fu_1124_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_2_phi_fu_424_p4) + unsigned(ap_const_lv32_1));
    add_ln97_4_fu_1210_p2 <= std_logic_vector(unsigned(zeros_added_2_3_reg_432) + unsigned(ap_const_lv32_1));
    add_ln97_5_fu_1300_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_4_phi_fu_445_p4) + unsigned(ap_const_lv32_1));
    add_ln97_6_fu_1389_p2 <= std_logic_vector(unsigned(zeros_added_2_5_reg_453) + unsigned(ap_const_lv32_1));
    add_ln97_7_fu_1492_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_6_phi_fu_466_p4) + unsigned(ap_const_lv32_1));
    add_ln97_8_fu_1595_p2 <= std_logic_vector(unsigned(zeros_added_2_7_reg_474) + unsigned(ap_const_lv32_1));
    add_ln97_9_fu_1698_p2 <= std_logic_vector(unsigned(ap_phi_mux_zeros_added_2_8_phi_fu_487_p4) + unsigned(ap_const_lv32_1));
    add_ln97_fu_842_p2 <= std_logic_vector(unsigned(zeros_added_0_reg_378) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state10, icmp_ln86_fu_719_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_zeros_added_0_be_phi_fu_561_p4_assign_proc : process(ap_CS_fsm_state17, ap_phi_mux_zeros_added_2_14_phi_fu_550_p4, add_ln97_15_fu_2313_p2, or_ln94_15_fu_2307_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
            if ((or_ln94_15_fu_2307_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 <= ap_phi_mux_zeros_added_2_14_phi_fu_550_p4;
            elsif ((or_ln94_15_fu_2307_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 <= add_ln97_15_fu_2313_p2;
            else 
                ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_0_be_phi_fu_561_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_0_phi_fu_403_p4_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, zeros_added_0_reg_378, add_ln97_fu_842_p2, or_ln94_fu_836_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0))) then
            if ((or_ln94_fu_836_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 <= zeros_added_0_reg_378;
            elsif ((or_ln94_fu_836_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 <= add_ln97_fu_842_p2;
            else 
                ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_0_phi_fu_403_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_10_phi_fu_508_p4_assign_proc : process(ap_CS_fsm_state15, zeros_added_2_9_reg_495, add_ln97_10_fu_1801_p2, or_ln94_10_fu_1795_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
            if ((or_ln94_10_fu_1795_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 <= zeros_added_2_9_reg_495;
            elsif ((or_ln94_10_fu_1795_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 <= add_ln97_10_fu_1801_p2;
            else 
                ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_10_phi_fu_508_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_12_phi_fu_529_p4_assign_proc : process(ap_CS_fsm_state16, zeros_added_2_11_reg_516, add_ln97_12_fu_2006_p2, or_ln94_12_fu_2000_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((or_ln94_12_fu_2000_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 <= zeros_added_2_11_reg_516;
            elsif ((or_ln94_12_fu_2000_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 <= add_ln97_12_fu_2006_p2;
            else 
                ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_12_phi_fu_529_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_14_phi_fu_550_p4_assign_proc : process(ap_CS_fsm_state17, zeros_added_2_13_reg_537, add_ln97_14_fu_2211_p2, or_ln94_14_fu_2205_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
            if ((or_ln94_14_fu_2205_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 <= zeros_added_2_13_reg_537;
            elsif ((or_ln94_14_fu_2205_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 <= add_ln97_14_fu_2211_p2;
            else 
                ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_14_phi_fu_550_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_2_phi_fu_424_p4_assign_proc : process(ap_CS_fsm_state11, zeros_added_2_1_reg_411, add_ln97_2_fu_1034_p2, or_ln94_2_fu_1028_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
            if ((or_ln94_2_fu_1028_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 <= zeros_added_2_1_reg_411;
            elsif ((or_ln94_2_fu_1028_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 <= add_ln97_2_fu_1034_p2;
            else 
                ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_2_phi_fu_424_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_4_phi_fu_445_p4_assign_proc : process(ap_CS_fsm_state12, zeros_added_2_3_reg_432, add_ln97_4_fu_1210_p2, or_ln94_4_fu_1204_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
            if ((or_ln94_4_fu_1204_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 <= zeros_added_2_3_reg_432;
            elsif ((or_ln94_4_fu_1204_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 <= add_ln97_4_fu_1210_p2;
            else 
                ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_4_phi_fu_445_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_6_phi_fu_466_p4_assign_proc : process(ap_CS_fsm_state13, zeros_added_2_5_reg_453, add_ln97_6_fu_1389_p2, or_ln94_6_fu_1383_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
            if ((or_ln94_6_fu_1383_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 <= zeros_added_2_5_reg_453;
            elsif ((or_ln94_6_fu_1383_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 <= add_ln97_6_fu_1389_p2;
            else 
                ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_6_phi_fu_466_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_zeros_added_2_8_phi_fu_487_p4_assign_proc : process(ap_CS_fsm_state14, zeros_added_2_7_reg_474, add_ln97_8_fu_1595_p2, or_ln94_8_fu_1589_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
            if ((or_ln94_8_fu_1589_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 <= zeros_added_2_7_reg_474;
            elsif ((or_ln94_8_fu_1589_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 <= add_ln97_8_fu_1595_p2;
            else 
                ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_zeros_added_2_8_phi_fu_487_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    global_lfsr_seed_V_o_assign_proc : process(global_lfsr_seed_V_i, ap_CS_fsm_state10, icmp_ln86_fu_719_p2, p_090_0_reg_368)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_1))) then 
            global_lfsr_seed_V_o <= p_090_0_reg_368;
        else 
            global_lfsr_seed_V_o <= global_lfsr_seed_V_i;
        end if; 
    end process;


    global_lfsr_seed_V_o_ap_vld_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_1))) then 
            global_lfsr_seed_V_o_ap_vld <= ap_const_logic_1;
        else 
            global_lfsr_seed_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_569_p0_assign_proc : process(ap_CS_fsm_state1, zero_percentage, tmp_reg_2325, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_569_p0 <= tmp_reg_2325;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_569_p0 <= zero_percentage;
        else 
            grp_fu_569_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_569_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_569_p1 <= ap_const_lv32_41800000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_569_p1 <= ap_const_lv32_42C80000;
        else 
            grp_fu_569_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    i_fu_725_p2 <= std_logic_vector(unsigned(i_0_reg_389) + unsigned(ap_const_lv7_1));
    icmp_ln86_fu_719_p2 <= "1" when (i_0_reg_389 = ap_const_lv7_64) else "0";
    icmp_ln94_10_fu_1779_p2 <= "1" when (signed(zeros_added_2_9_reg_495) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_11_fu_1880_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_10_phi_fu_508_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_12_fu_1984_p2 <= "1" when (signed(zeros_added_2_11_reg_516) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_13_fu_2085_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_12_phi_fu_529_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_14_fu_2189_p2 <= "1" when (signed(zeros_added_2_13_reg_537) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_15_fu_2290_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_14_phi_fu_550_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_1_fu_919_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_0_phi_fu_403_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_2_fu_1011_p2 <= "1" when (signed(zeros_added_2_1_reg_411) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_3_fu_1101_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_2_phi_fu_424_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_4_fu_1187_p2 <= "1" when (signed(zeros_added_2_3_reg_432) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_5_fu_1277_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_4_phi_fu_445_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_6_fu_1366_p2 <= "1" when (signed(zeros_added_2_5_reg_453) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_7_fu_1469_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_6_phi_fu_466_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_8_fu_1572_p2 <= "1" when (signed(zeros_added_2_7_reg_474) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_9_fu_1675_p2 <= "1" when (signed(ap_phi_mux_zeros_added_2_8_phi_fu_487_p4) < signed(p_Val2_6_reg_2351)) else "0";
    icmp_ln94_fu_819_p2 <= "1" when (signed(zeros_added_0_reg_378) < signed(p_Val2_6_reg_2351)) else "0";
    isNeg_fu_612_p3 <= add_ln339_fu_606_p2(8 downto 8);
    mantissa_V_fu_638_p4 <= ((ap_const_lv1_1 & tmp_V_1_reg_2335) & ap_const_lv1_0);
    matrix_0_address0 <= zext_ln96_fu_731_p1(7 - 1 downto 0);

    matrix_0_ce0_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, or_ln94_fu_836_p2)
    begin
        if ((((or_ln94_fu_836_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln94_fu_836_p2 = ap_const_lv1_0) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)))) then 
            matrix_0_ce0 <= ap_const_logic_1;
        else 
            matrix_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_0_d0_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, or_ln94_fu_836_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0))) then
            if ((or_ln94_fu_836_p2 = ap_const_lv1_1)) then 
                matrix_0_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_fu_836_p2 = ap_const_lv1_0)) then 
                matrix_0_d0 <= ap_const_lv1_0;
            else 
                matrix_0_d0 <= "X";
            end if;
        else 
            matrix_0_d0 <= "X";
        end if; 
    end process;


    matrix_0_we0_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, or_ln94_fu_836_p2)
    begin
        if ((((or_ln94_fu_836_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln94_fu_836_p2 = ap_const_lv1_0) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)))) then 
            matrix_0_we0 <= ap_const_logic_1;
        else 
            matrix_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_10_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_10_ce0_assign_proc : process(ap_CS_fsm_state15, or_ln94_10_fu_1795_p2)
    begin
        if ((((or_ln94_10_fu_1795_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15)) or ((ap_const_logic_1 = ap_CS_fsm_state15) and (or_ln94_10_fu_1795_p2 = ap_const_lv1_0)))) then 
            matrix_10_ce0 <= ap_const_logic_1;
        else 
            matrix_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_10_d0_assign_proc : process(ap_CS_fsm_state15, or_ln94_10_fu_1795_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
            if ((or_ln94_10_fu_1795_p2 = ap_const_lv1_1)) then 
                matrix_10_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_10_fu_1795_p2 = ap_const_lv1_0)) then 
                matrix_10_d0 <= ap_const_lv1_0;
            else 
                matrix_10_d0 <= "X";
            end if;
        else 
            matrix_10_d0 <= "X";
        end if; 
    end process;


    matrix_10_we0_assign_proc : process(ap_CS_fsm_state15, or_ln94_10_fu_1795_p2)
    begin
        if ((((or_ln94_10_fu_1795_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15)) or ((ap_const_logic_1 = ap_CS_fsm_state15) and (or_ln94_10_fu_1795_p2 = ap_const_lv1_0)))) then 
            matrix_10_we0 <= ap_const_logic_1;
        else 
            matrix_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_11_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_11_ce0_assign_proc : process(ap_CS_fsm_state15, or_ln94_11_fu_1897_p2)
    begin
        if ((((or_ln94_11_fu_1897_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15)) or ((ap_const_logic_1 = ap_CS_fsm_state15) and (or_ln94_11_fu_1897_p2 = ap_const_lv1_0)))) then 
            matrix_11_ce0 <= ap_const_logic_1;
        else 
            matrix_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_11_d0_assign_proc : process(ap_CS_fsm_state15, or_ln94_11_fu_1897_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
            if ((or_ln94_11_fu_1897_p2 = ap_const_lv1_1)) then 
                matrix_11_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_11_fu_1897_p2 = ap_const_lv1_0)) then 
                matrix_11_d0 <= ap_const_lv1_0;
            else 
                matrix_11_d0 <= "X";
            end if;
        else 
            matrix_11_d0 <= "X";
        end if; 
    end process;


    matrix_11_we0_assign_proc : process(ap_CS_fsm_state15, or_ln94_11_fu_1897_p2)
    begin
        if ((((or_ln94_11_fu_1897_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15)) or ((ap_const_logic_1 = ap_CS_fsm_state15) and (or_ln94_11_fu_1897_p2 = ap_const_lv1_0)))) then 
            matrix_11_we0 <= ap_const_logic_1;
        else 
            matrix_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_12_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_12_ce0_assign_proc : process(ap_CS_fsm_state16, or_ln94_12_fu_2000_p2)
    begin
        if ((((or_ln94_12_fu_2000_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((ap_const_logic_1 = ap_CS_fsm_state16) and (or_ln94_12_fu_2000_p2 = ap_const_lv1_0)))) then 
            matrix_12_ce0 <= ap_const_logic_1;
        else 
            matrix_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_12_d0_assign_proc : process(ap_CS_fsm_state16, or_ln94_12_fu_2000_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((or_ln94_12_fu_2000_p2 = ap_const_lv1_1)) then 
                matrix_12_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_12_fu_2000_p2 = ap_const_lv1_0)) then 
                matrix_12_d0 <= ap_const_lv1_0;
            else 
                matrix_12_d0 <= "X";
            end if;
        else 
            matrix_12_d0 <= "X";
        end if; 
    end process;


    matrix_12_we0_assign_proc : process(ap_CS_fsm_state16, or_ln94_12_fu_2000_p2)
    begin
        if ((((or_ln94_12_fu_2000_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((ap_const_logic_1 = ap_CS_fsm_state16) and (or_ln94_12_fu_2000_p2 = ap_const_lv1_0)))) then 
            matrix_12_we0 <= ap_const_logic_1;
        else 
            matrix_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_13_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_13_ce0_assign_proc : process(ap_CS_fsm_state16, or_ln94_13_fu_2102_p2)
    begin
        if ((((or_ln94_13_fu_2102_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((ap_const_logic_1 = ap_CS_fsm_state16) and (or_ln94_13_fu_2102_p2 = ap_const_lv1_0)))) then 
            matrix_13_ce0 <= ap_const_logic_1;
        else 
            matrix_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_13_d0_assign_proc : process(ap_CS_fsm_state16, or_ln94_13_fu_2102_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((or_ln94_13_fu_2102_p2 = ap_const_lv1_1)) then 
                matrix_13_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_13_fu_2102_p2 = ap_const_lv1_0)) then 
                matrix_13_d0 <= ap_const_lv1_0;
            else 
                matrix_13_d0 <= "X";
            end if;
        else 
            matrix_13_d0 <= "X";
        end if; 
    end process;


    matrix_13_we0_assign_proc : process(ap_CS_fsm_state16, or_ln94_13_fu_2102_p2)
    begin
        if ((((or_ln94_13_fu_2102_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((ap_const_logic_1 = ap_CS_fsm_state16) and (or_ln94_13_fu_2102_p2 = ap_const_lv1_0)))) then 
            matrix_13_we0 <= ap_const_logic_1;
        else 
            matrix_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_14_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_14_ce0_assign_proc : process(ap_CS_fsm_state17, or_ln94_14_fu_2205_p2)
    begin
        if ((((or_ln94_14_fu_2205_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17)) or ((ap_const_logic_1 = ap_CS_fsm_state17) and (or_ln94_14_fu_2205_p2 = ap_const_lv1_0)))) then 
            matrix_14_ce0 <= ap_const_logic_1;
        else 
            matrix_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_14_d0_assign_proc : process(ap_CS_fsm_state17, or_ln94_14_fu_2205_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
            if ((or_ln94_14_fu_2205_p2 = ap_const_lv1_1)) then 
                matrix_14_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_14_fu_2205_p2 = ap_const_lv1_0)) then 
                matrix_14_d0 <= ap_const_lv1_0;
            else 
                matrix_14_d0 <= "X";
            end if;
        else 
            matrix_14_d0 <= "X";
        end if; 
    end process;


    matrix_14_we0_assign_proc : process(ap_CS_fsm_state17, or_ln94_14_fu_2205_p2)
    begin
        if ((((or_ln94_14_fu_2205_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17)) or ((ap_const_logic_1 = ap_CS_fsm_state17) and (or_ln94_14_fu_2205_p2 = ap_const_lv1_0)))) then 
            matrix_14_we0 <= ap_const_logic_1;
        else 
            matrix_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_15_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_15_ce0_assign_proc : process(ap_CS_fsm_state17, or_ln94_15_fu_2307_p2)
    begin
        if ((((or_ln94_15_fu_2307_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17)) or ((ap_const_logic_1 = ap_CS_fsm_state17) and (or_ln94_15_fu_2307_p2 = ap_const_lv1_0)))) then 
            matrix_15_ce0 <= ap_const_logic_1;
        else 
            matrix_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_15_d0_assign_proc : process(ap_CS_fsm_state17, or_ln94_15_fu_2307_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
            if ((or_ln94_15_fu_2307_p2 = ap_const_lv1_1)) then 
                matrix_15_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_15_fu_2307_p2 = ap_const_lv1_0)) then 
                matrix_15_d0 <= ap_const_lv1_0;
            else 
                matrix_15_d0 <= "X";
            end if;
        else 
            matrix_15_d0 <= "X";
        end if; 
    end process;


    matrix_15_we0_assign_proc : process(ap_CS_fsm_state17, or_ln94_15_fu_2307_p2)
    begin
        if ((((or_ln94_15_fu_2307_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17)) or ((ap_const_logic_1 = ap_CS_fsm_state17) and (or_ln94_15_fu_2307_p2 = ap_const_lv1_0)))) then 
            matrix_15_we0 <= ap_const_logic_1;
        else 
            matrix_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_1_address0 <= zext_ln96_fu_731_p1(7 - 1 downto 0);

    matrix_1_ce0_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, or_ln94_1_fu_936_p2)
    begin
        if ((((or_ln94_1_fu_936_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln94_1_fu_936_p2 = ap_const_lv1_0) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)))) then 
            matrix_1_ce0 <= ap_const_logic_1;
        else 
            matrix_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_1_d0_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, or_ln94_1_fu_936_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0))) then
            if ((or_ln94_1_fu_936_p2 = ap_const_lv1_1)) then 
                matrix_1_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_1_fu_936_p2 = ap_const_lv1_0)) then 
                matrix_1_d0 <= ap_const_lv1_0;
            else 
                matrix_1_d0 <= "X";
            end if;
        else 
            matrix_1_d0 <= "X";
        end if; 
    end process;


    matrix_1_we0_assign_proc : process(ap_CS_fsm_state10, icmp_ln86_fu_719_p2, or_ln94_1_fu_936_p2)
    begin
        if ((((or_ln94_1_fu_936_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln94_1_fu_936_p2 = ap_const_lv1_0) and (icmp_ln86_fu_719_p2 = ap_const_lv1_0)))) then 
            matrix_1_we0 <= ap_const_logic_1;
        else 
            matrix_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_2_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_2_ce0_assign_proc : process(ap_CS_fsm_state11, or_ln94_2_fu_1028_p2)
    begin
        if ((((or_ln94_2_fu_1028_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_logic_1 = ap_CS_fsm_state11) and (or_ln94_2_fu_1028_p2 = ap_const_lv1_0)))) then 
            matrix_2_ce0 <= ap_const_logic_1;
        else 
            matrix_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_2_d0_assign_proc : process(ap_CS_fsm_state11, or_ln94_2_fu_1028_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
            if ((or_ln94_2_fu_1028_p2 = ap_const_lv1_1)) then 
                matrix_2_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_2_fu_1028_p2 = ap_const_lv1_0)) then 
                matrix_2_d0 <= ap_const_lv1_0;
            else 
                matrix_2_d0 <= "X";
            end if;
        else 
            matrix_2_d0 <= "X";
        end if; 
    end process;


    matrix_2_we0_assign_proc : process(ap_CS_fsm_state11, or_ln94_2_fu_1028_p2)
    begin
        if ((((or_ln94_2_fu_1028_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_logic_1 = ap_CS_fsm_state11) and (or_ln94_2_fu_1028_p2 = ap_const_lv1_0)))) then 
            matrix_2_we0 <= ap_const_logic_1;
        else 
            matrix_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_3_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_3_ce0_assign_proc : process(ap_CS_fsm_state11, or_ln94_3_fu_1118_p2)
    begin
        if ((((or_ln94_3_fu_1118_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_logic_1 = ap_CS_fsm_state11) and (or_ln94_3_fu_1118_p2 = ap_const_lv1_0)))) then 
            matrix_3_ce0 <= ap_const_logic_1;
        else 
            matrix_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_3_d0_assign_proc : process(ap_CS_fsm_state11, or_ln94_3_fu_1118_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
            if ((or_ln94_3_fu_1118_p2 = ap_const_lv1_1)) then 
                matrix_3_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_3_fu_1118_p2 = ap_const_lv1_0)) then 
                matrix_3_d0 <= ap_const_lv1_0;
            else 
                matrix_3_d0 <= "X";
            end if;
        else 
            matrix_3_d0 <= "X";
        end if; 
    end process;


    matrix_3_we0_assign_proc : process(ap_CS_fsm_state11, or_ln94_3_fu_1118_p2)
    begin
        if ((((or_ln94_3_fu_1118_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_logic_1 = ap_CS_fsm_state11) and (or_ln94_3_fu_1118_p2 = ap_const_lv1_0)))) then 
            matrix_3_we0 <= ap_const_logic_1;
        else 
            matrix_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_4_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_4_ce0_assign_proc : process(ap_CS_fsm_state12, or_ln94_4_fu_1204_p2)
    begin
        if ((((or_ln94_4_fu_1204_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (or_ln94_4_fu_1204_p2 = ap_const_lv1_0)))) then 
            matrix_4_ce0 <= ap_const_logic_1;
        else 
            matrix_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_4_d0_assign_proc : process(ap_CS_fsm_state12, or_ln94_4_fu_1204_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
            if ((or_ln94_4_fu_1204_p2 = ap_const_lv1_1)) then 
                matrix_4_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_4_fu_1204_p2 = ap_const_lv1_0)) then 
                matrix_4_d0 <= ap_const_lv1_0;
            else 
                matrix_4_d0 <= "X";
            end if;
        else 
            matrix_4_d0 <= "X";
        end if; 
    end process;


    matrix_4_we0_assign_proc : process(ap_CS_fsm_state12, or_ln94_4_fu_1204_p2)
    begin
        if ((((or_ln94_4_fu_1204_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (or_ln94_4_fu_1204_p2 = ap_const_lv1_0)))) then 
            matrix_4_we0 <= ap_const_logic_1;
        else 
            matrix_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_5_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_5_ce0_assign_proc : process(ap_CS_fsm_state12, or_ln94_5_fu_1294_p2)
    begin
        if ((((or_ln94_5_fu_1294_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (or_ln94_5_fu_1294_p2 = ap_const_lv1_0)))) then 
            matrix_5_ce0 <= ap_const_logic_1;
        else 
            matrix_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_5_d0_assign_proc : process(ap_CS_fsm_state12, or_ln94_5_fu_1294_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
            if ((or_ln94_5_fu_1294_p2 = ap_const_lv1_1)) then 
                matrix_5_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_5_fu_1294_p2 = ap_const_lv1_0)) then 
                matrix_5_d0 <= ap_const_lv1_0;
            else 
                matrix_5_d0 <= "X";
            end if;
        else 
            matrix_5_d0 <= "X";
        end if; 
    end process;


    matrix_5_we0_assign_proc : process(ap_CS_fsm_state12, or_ln94_5_fu_1294_p2)
    begin
        if ((((or_ln94_5_fu_1294_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (or_ln94_5_fu_1294_p2 = ap_const_lv1_0)))) then 
            matrix_5_we0 <= ap_const_logic_1;
        else 
            matrix_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_6_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_6_ce0_assign_proc : process(ap_CS_fsm_state13, or_ln94_6_fu_1383_p2)
    begin
        if ((((or_ln94_6_fu_1383_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and (or_ln94_6_fu_1383_p2 = ap_const_lv1_0)))) then 
            matrix_6_ce0 <= ap_const_logic_1;
        else 
            matrix_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_6_d0_assign_proc : process(ap_CS_fsm_state13, or_ln94_6_fu_1383_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
            if ((or_ln94_6_fu_1383_p2 = ap_const_lv1_1)) then 
                matrix_6_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_6_fu_1383_p2 = ap_const_lv1_0)) then 
                matrix_6_d0 <= ap_const_lv1_0;
            else 
                matrix_6_d0 <= "X";
            end if;
        else 
            matrix_6_d0 <= "X";
        end if; 
    end process;


    matrix_6_we0_assign_proc : process(ap_CS_fsm_state13, or_ln94_6_fu_1383_p2)
    begin
        if ((((or_ln94_6_fu_1383_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and (or_ln94_6_fu_1383_p2 = ap_const_lv1_0)))) then 
            matrix_6_we0 <= ap_const_logic_1;
        else 
            matrix_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_7_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_7_ce0_assign_proc : process(ap_CS_fsm_state13, or_ln94_7_fu_1486_p2)
    begin
        if ((((or_ln94_7_fu_1486_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and (or_ln94_7_fu_1486_p2 = ap_const_lv1_0)))) then 
            matrix_7_ce0 <= ap_const_logic_1;
        else 
            matrix_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_7_d0_assign_proc : process(ap_CS_fsm_state13, or_ln94_7_fu_1486_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
            if ((or_ln94_7_fu_1486_p2 = ap_const_lv1_1)) then 
                matrix_7_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_7_fu_1486_p2 = ap_const_lv1_0)) then 
                matrix_7_d0 <= ap_const_lv1_0;
            else 
                matrix_7_d0 <= "X";
            end if;
        else 
            matrix_7_d0 <= "X";
        end if; 
    end process;


    matrix_7_we0_assign_proc : process(ap_CS_fsm_state13, or_ln94_7_fu_1486_p2)
    begin
        if ((((or_ln94_7_fu_1486_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and (or_ln94_7_fu_1486_p2 = ap_const_lv1_0)))) then 
            matrix_7_we0 <= ap_const_logic_1;
        else 
            matrix_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_8_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_8_ce0_assign_proc : process(ap_CS_fsm_state14, or_ln94_8_fu_1589_p2)
    begin
        if ((((or_ln94_8_fu_1589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln94_8_fu_1589_p2 = ap_const_lv1_0)))) then 
            matrix_8_ce0 <= ap_const_logic_1;
        else 
            matrix_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_8_d0_assign_proc : process(ap_CS_fsm_state14, or_ln94_8_fu_1589_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
            if ((or_ln94_8_fu_1589_p2 = ap_const_lv1_1)) then 
                matrix_8_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_8_fu_1589_p2 = ap_const_lv1_0)) then 
                matrix_8_d0 <= ap_const_lv1_0;
            else 
                matrix_8_d0 <= "X";
            end if;
        else 
            matrix_8_d0 <= "X";
        end if; 
    end process;


    matrix_8_we0_assign_proc : process(ap_CS_fsm_state14, or_ln94_8_fu_1589_p2)
    begin
        if ((((or_ln94_8_fu_1589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln94_8_fu_1589_p2 = ap_const_lv1_0)))) then 
            matrix_8_we0 <= ap_const_logic_1;
        else 
            matrix_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_9_address0 <= zext_ln96_reg_2384(7 - 1 downto 0);

    matrix_9_ce0_assign_proc : process(ap_CS_fsm_state14, or_ln94_9_fu_1692_p2)
    begin
        if ((((or_ln94_9_fu_1692_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln94_9_fu_1692_p2 = ap_const_lv1_0)))) then 
            matrix_9_ce0 <= ap_const_logic_1;
        else 
            matrix_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_9_d0_assign_proc : process(ap_CS_fsm_state14, or_ln94_9_fu_1692_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
            if ((or_ln94_9_fu_1692_p2 = ap_const_lv1_1)) then 
                matrix_9_d0 <= ap_const_lv1_1;
            elsif ((or_ln94_9_fu_1692_p2 = ap_const_lv1_0)) then 
                matrix_9_d0 <= ap_const_lv1_0;
            else 
                matrix_9_d0 <= "X";
            end if;
        else 
            matrix_9_d0 <= "X";
        end if; 
    end process;


    matrix_9_we0_assign_proc : process(ap_CS_fsm_state14, or_ln94_9_fu_1692_p2)
    begin
        if ((((or_ln94_9_fu_1692_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln94_9_fu_1692_p2 = ap_const_lv1_0)))) then 
            matrix_9_we0 <= ap_const_logic_1;
        else 
            matrix_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln68_10_fu_1773_p2 <= (shl_ln68_s_fu_1765_p3 or sext_ln1503_10_fu_1735_p1);
    or_ln68_11_fu_1874_p2 <= (shl_ln68_10_fu_1866_p3 or sext_ln1503_11_fu_1838_p1);
    or_ln68_12_fu_1978_p2 <= (shl_ln68_11_fu_1970_p3 or sext_ln1503_12_fu_1940_p1);
    or_ln68_13_fu_2079_p2 <= (shl_ln68_12_fu_2071_p3 or sext_ln1503_13_fu_2043_p1);
    or_ln68_14_fu_2183_p2 <= (shl_ln68_13_fu_2175_p3 or sext_ln1503_14_fu_2145_p1);
    or_ln68_15_fu_2284_p2 <= (shl_ln68_14_fu_2276_p3 or sext_ln1503_15_fu_2248_p1);
    or_ln68_1_fu_913_p2 <= (shl_ln68_1_fu_905_p3 or sext_ln1503_1_fu_875_p1);
    or_ln68_2_fu_1005_p2 <= (shl_ln68_2_fu_997_p3 or sext_ln1503_2_fu_971_p1);
    or_ln68_3_fu_1095_p2 <= (shl_ln68_3_fu_1087_p3 or sext_ln1503_3_fu_1059_p1);
    or_ln68_4_fu_1181_p2 <= (shl_ln68_4_fu_1173_p3 or sext_ln1503_4_fu_1147_p1);
    or_ln68_5_fu_1271_p2 <= (shl_ln68_5_fu_1263_p3 or sext_ln1503_5_fu_1235_p1);
    or_ln68_6_fu_1353_p2 <= (shl_ln68_6_fu_1345_p3 or sext_ln1503_6_fu_1324_p1);
    or_ln68_7_fu_1463_p2 <= (shl_ln68_7_fu_1455_p3 or sext_ln1503_7_fu_1426_p1);
    or_ln68_8_fu_1559_p2 <= (shl_ln68_8_fu_1551_p3 or sext_ln1503_8_fu_1529_p1);
    or_ln68_9_fu_1669_p2 <= (shl_ln68_9_fu_1661_p3 or sext_ln1503_9_fu_1632_p1);
    or_ln68_fu_813_p2 <= (shl_ln_fu_805_p3 or sext_ln1503_fu_775_p1);
    or_ln94_10_fu_1795_p2 <= (xor_ln94_26_fu_1784_p2 or xor_ln94_10_fu_1790_p2);
    or_ln94_11_fu_1897_p2 <= (xor_ln94_27_fu_1885_p2 or xor_ln94_11_fu_1891_p2);
    or_ln94_12_fu_2000_p2 <= (xor_ln94_28_fu_1989_p2 or xor_ln94_12_fu_1995_p2);
    or_ln94_13_fu_2102_p2 <= (xor_ln94_29_fu_2090_p2 or xor_ln94_13_fu_2096_p2);
    or_ln94_14_fu_2205_p2 <= (xor_ln94_30_fu_2194_p2 or xor_ln94_14_fu_2200_p2);
    or_ln94_15_fu_2307_p2 <= (xor_ln94_31_fu_2295_p2 or xor_ln94_15_fu_2301_p2);
    or_ln94_1_fu_936_p2 <= (xor_ln94_1_fu_930_p2 or xor_ln94_17_fu_924_p2);
    or_ln94_2_fu_1028_p2 <= (xor_ln94_2_fu_1022_p2 or xor_ln94_18_fu_1016_p2);
    or_ln94_3_fu_1118_p2 <= (xor_ln94_3_fu_1112_p2 or xor_ln94_19_fu_1106_p2);
    or_ln94_4_fu_1204_p2 <= (xor_ln94_4_fu_1198_p2 or xor_ln94_20_fu_1192_p2);
    or_ln94_5_fu_1294_p2 <= (xor_ln94_5_fu_1288_p2 or xor_ln94_21_fu_1282_p2);
    or_ln94_6_fu_1383_p2 <= (xor_ln94_6_fu_1377_p2 or xor_ln94_22_fu_1371_p2);
    or_ln94_7_fu_1486_p2 <= (xor_ln94_7_fu_1480_p2 or xor_ln94_23_fu_1474_p2);
    or_ln94_8_fu_1589_p2 <= (xor_ln94_8_fu_1583_p2 or xor_ln94_24_fu_1577_p2);
    or_ln94_9_fu_1692_p2 <= (xor_ln94_9_fu_1686_p2 or xor_ln94_25_fu_1680_p2);
    or_ln94_fu_836_p2 <= (xor_ln94_fu_830_p2 or xor_ln94_16_fu_824_p2);
    p_Val2_5_fu_695_p3 <= 
        zext_ln662_fu_681_p1 when (isNeg_reg_2340(0) = '1') else 
        tmp_s_fu_685_p4;
    p_Val2_6_fu_708_p3 <= 
        result_V_1_fu_702_p2 when (p_Result_s_reg_2330(0) = '1') else 
        p_Val2_5_fu_695_p3;
    p_Val2_s_fu_576_p1 <= grp_fu_569_p2;
    r_V_1_fu_667_p2 <= std_logic_vector(shift_left(unsigned(zext_ln682_fu_647_p1),to_integer(unsigned('0' & zext_ln1287_fu_657_p1(31-1 downto 0)))));
    r_V_fu_661_p2 <= std_logic_vector(shift_right(unsigned(mantissa_V_fu_638_p4),to_integer(unsigned('0' & sext_ln1311_2_fu_654_p1(25-1 downto 0)))));
    result_V_1_fu_702_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(p_Val2_5_fu_695_p3));
        sext_ln1311_1_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_2345),32));

        sext_ln1311_2_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_2345),25));

        sext_ln1311_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1311_fu_620_p2),9));

        sext_ln1503_10_fu_1735_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_9_fu_1725_p4),16));

        sext_ln1503_11_fu_1838_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_10_fu_1829_p4),16));

        sext_ln1503_12_fu_1940_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_11_fu_1930_p4),16));

        sext_ln1503_13_fu_2043_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_12_fu_2034_p4),16));

        sext_ln1503_14_fu_2145_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_13_fu_2135_p4),16));

        sext_ln1503_15_fu_2248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_14_fu_2239_p4),16));

        sext_ln1503_1_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_s_fu_865_p4),16));

        sext_ln1503_2_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_1_fu_962_p4),16));

        sext_ln1503_3_fu_1059_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_2_fu_1049_p4),16));

        sext_ln1503_4_fu_1147_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_3_fu_1138_p4),16));

        sext_ln1503_5_fu_1235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_4_fu_1225_p4),16));

        sext_ln1503_6_fu_1324_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_5_fu_1314_p4),16));

        sext_ln1503_7_fu_1426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_6_fu_1417_p4),16));

        sext_ln1503_8_fu_1529_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_7_fu_1519_p4),16));

        sext_ln1503_9_fu_1632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1503_8_fu_1623_p4),16));

        sext_ln1503_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln3_fu_765_p4),16));

    shl_ln68_10_fu_1866_p3 <= (xor_ln68_35_fu_1860_p2 & ap_const_lv15_0);
    shl_ln68_11_fu_1970_p3 <= (xor_ln68_38_fu_1964_p2 & ap_const_lv15_0);
    shl_ln68_12_fu_2071_p3 <= (xor_ln68_41_fu_2065_p2 & ap_const_lv15_0);
    shl_ln68_13_fu_2175_p3 <= (xor_ln68_44_fu_2169_p2 & ap_const_lv15_0);
    shl_ln68_14_fu_2276_p3 <= (xor_ln68_47_fu_2270_p2 & ap_const_lv15_0);
    shl_ln68_1_fu_905_p3 <= (xor_ln68_5_fu_899_p2 & ap_const_lv15_0);
    shl_ln68_2_fu_997_p3 <= (xor_ln68_8_fu_991_p2 & ap_const_lv15_0);
    shl_ln68_3_fu_1087_p3 <= (xor_ln68_11_fu_1081_p2 & ap_const_lv15_0);
    shl_ln68_4_fu_1173_p3 <= (xor_ln68_14_fu_1167_p2 & ap_const_lv15_0);
    shl_ln68_5_fu_1263_p3 <= (xor_ln68_17_fu_1257_p2 & ap_const_lv15_0);
    shl_ln68_6_fu_1345_p3 <= (xor_ln68_20_fu_1339_p2 & ap_const_lv15_0);
    shl_ln68_7_fu_1455_p3 <= (xor_ln68_23_fu_1449_p2 & ap_const_lv15_0);
    shl_ln68_8_fu_1551_p3 <= (xor_ln68_26_fu_1545_p2 & ap_const_lv15_0);
    shl_ln68_9_fu_1661_p3 <= (xor_ln68_29_fu_1655_p2 & ap_const_lv15_0);
    shl_ln68_s_fu_1765_p3 <= (xor_ln68_32_fu_1759_p2 & ap_const_lv15_0);
    shl_ln_fu_805_p3 <= (xor_ln68_fu_799_p2 & ap_const_lv15_0);
    sub_ln1311_fu_620_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(tmp_V_fu_588_p4));
    tmp_133_fu_673_p3 <= r_V_fu_661_p2(24 downto 24);
    tmp_134_fu_741_p3 <= p_090_0_reg_368(2 downto 2);
    tmp_135_fu_749_p3 <= p_090_0_reg_368(3 downto 3);
    tmp_136_fu_757_p3 <= p_090_0_reg_368(5 downto 5);
    tmp_137_fu_779_p3 <= p_090_0_reg_368(1 downto 1);
    tmp_138_fu_849_p3 <= p_090_0_reg_368(4 downto 4);
    tmp_139_fu_857_p3 <= p_090_0_reg_368(6 downto 6);
    tmp_140_fu_879_p3 <= or_ln68_fu_813_p2(1 downto 1);
    tmp_141_fu_954_p3 <= p_090_0_reg_368(7 downto 7);
    tmp_142_fu_975_p3 <= or_ln68_1_reg_2434(1 downto 1);
    tmp_143_fu_1041_p3 <= p_090_0_reg_368(8 downto 8);
    tmp_144_fu_1063_p3 <= or_ln68_2_fu_1005_p2(1 downto 1);
    tmp_145_fu_1130_p3 <= p_090_0_reg_368(9 downto 9);
    tmp_146_fu_1151_p3 <= or_ln68_3_reg_2478(1 downto 1);
    tmp_147_fu_1217_p3 <= p_090_0_reg_368(10 downto 10);
    tmp_148_fu_1239_p3 <= or_ln68_4_fu_1181_p2(1 downto 1);
    tmp_149_fu_1306_p3 <= p_090_0_reg_368(11 downto 11);
    tmp_150_fu_1359_p3 <= or_ln68_5_reg_2505(1 downto 1);
    tmp_151_fu_1396_p3 <= or_ln68_reg_2408(8 downto 8);
    tmp_152_fu_1403_p3 <= or_ln68_reg_2408(9 downto 9);
    tmp_153_fu_1410_p3 <= or_ln68_reg_2408(11 downto 11);
    tmp_154_fu_1430_p3 <= or_ln68_6_reg_2521(1 downto 1);
    tmp_155_fu_1498_p3 <= or_ln68_1_reg_2434(8 downto 8);
    tmp_156_fu_1505_p3 <= or_ln68_1_reg_2434(9 downto 9);
    tmp_157_fu_1512_p3 <= or_ln68_1_reg_2434(11 downto 11);
    tmp_158_fu_1565_p3 <= or_ln68_7_reg_2533(1 downto 1);
    tmp_159_fu_1602_p3 <= or_ln68_2_reg_2457(8 downto 8);
    tmp_160_fu_1609_p3 <= or_ln68_2_reg_2457(9 downto 9);
    tmp_161_fu_1616_p3 <= or_ln68_2_reg_2457(11 downto 11);
    tmp_162_fu_1636_p3 <= or_ln68_8_reg_2549(1 downto 1);
    tmp_163_fu_1704_p3 <= or_ln68_3_reg_2478(8 downto 8);
    tmp_164_fu_1711_p3 <= or_ln68_3_reg_2478(9 downto 9);
    tmp_165_fu_1718_p3 <= or_ln68_3_reg_2478(11 downto 11);
    tmp_167_fu_1808_p3 <= or_ln68_4_reg_2495(8 downto 8);
    tmp_168_fu_1815_p3 <= or_ln68_4_reg_2495(9 downto 9);
    tmp_169_fu_1822_p3 <= or_ln68_4_reg_2495(11 downto 11);
    tmp_170_fu_1842_p3 <= or_ln68_10_reg_2575(1 downto 1);
    tmp_171_fu_1909_p3 <= or_ln68_5_reg_2505(8 downto 8);
    tmp_172_fu_1916_p3 <= or_ln68_5_reg_2505(9 downto 9);
    tmp_173_fu_1923_p3 <= or_ln68_5_reg_2505(11 downto 11);
    tmp_175_fu_2013_p3 <= or_ln68_6_reg_2521(8 downto 8);
    tmp_176_fu_2020_p3 <= or_ln68_6_reg_2521(9 downto 9);
    tmp_177_fu_2027_p3 <= or_ln68_6_reg_2521(11 downto 11);
    tmp_178_fu_2047_p3 <= or_ln68_12_reg_2598(1 downto 1);
    tmp_179_fu_2114_p3 <= or_ln68_7_reg_2533(8 downto 8);
    tmp_180_fu_2121_p3 <= or_ln68_7_reg_2533(9 downto 9);
    tmp_181_fu_2128_p3 <= or_ln68_7_reg_2533(11 downto 11);
    tmp_183_fu_2218_p3 <= or_ln68_8_reg_2549(8 downto 8);
    tmp_184_fu_2225_p3 <= or_ln68_8_reg_2549(9 downto 9);
    tmp_185_fu_2232_p3 <= or_ln68_8_reg_2549(11 downto 11);
    tmp_186_fu_2252_p3 <= or_ln68_14_reg_2621(1 downto 1);
    tmp_V_1_fu_598_p1 <= p_Val2_s_fu_576_p1(23 - 1 downto 0);
    tmp_V_fu_588_p4 <= p_Val2_s_fu_576_p1(30 downto 23);
    tmp_s_fu_685_p4 <= r_V_1_fu_667_p2(55 downto 24);
    trunc_ln1503_10_fu_1829_p4 <= or_ln68_10_reg_2575(15 downto 1);
    trunc_ln1503_11_fu_1930_p4 <= or_ln68_11_fu_1874_p2(15 downto 1);
    trunc_ln1503_12_fu_2034_p4 <= or_ln68_12_reg_2598(15 downto 1);
    trunc_ln1503_13_fu_2135_p4 <= or_ln68_13_fu_2079_p2(15 downto 1);
    trunc_ln1503_14_fu_2239_p4 <= or_ln68_14_reg_2621(15 downto 1);
    trunc_ln1503_1_fu_962_p4 <= or_ln68_1_reg_2434(15 downto 1);
    trunc_ln1503_2_fu_1049_p4 <= or_ln68_2_fu_1005_p2(15 downto 1);
    trunc_ln1503_3_fu_1138_p4 <= or_ln68_3_reg_2478(15 downto 1);
    trunc_ln1503_4_fu_1225_p4 <= or_ln68_4_fu_1181_p2(15 downto 1);
    trunc_ln1503_5_fu_1314_p4 <= or_ln68_5_fu_1271_p2(15 downto 1);
    trunc_ln1503_6_fu_1417_p4 <= or_ln68_6_reg_2521(15 downto 1);
    trunc_ln1503_7_fu_1519_p4 <= or_ln68_7_fu_1463_p2(15 downto 1);
    trunc_ln1503_8_fu_1623_p4 <= or_ln68_8_reg_2549(15 downto 1);
    trunc_ln1503_9_fu_1725_p4 <= or_ln68_9_fu_1669_p2(15 downto 1);
    trunc_ln1503_s_fu_865_p4 <= or_ln68_fu_813_p2(15 downto 1);
    trunc_ln3_fu_765_p4 <= p_090_0_reg_368(15 downto 1);
    trunc_ln91_fu_737_p1 <= p_090_0_reg_368(1 - 1 downto 0);
    ush_fu_630_p3 <= 
        sext_ln1311_fu_626_p1 when (isNeg_fu_612_p3(0) = '1') else 
        add_ln339_fu_606_p2;
    xor_ln68_10_fu_1076_p2 <= (tmp_143_fu_1041_p3 xor tmp_139_reg_2423);
    xor_ln68_11_fu_1081_p2 <= (xor_ln68_9_fu_1071_p2 xor xor_ln68_10_fu_1076_p2);
    xor_ln68_12_fu_1158_p2 <= (tmp_144_reg_2473 xor tmp_139_reg_2423);
    xor_ln68_13_fu_1162_p2 <= (tmp_145_fu_1130_p3 xor tmp_141_reg_2451);
    xor_ln68_14_fu_1167_p2 <= (xor_ln68_13_fu_1162_p2 xor xor_ln68_12_fu_1158_p2);
    xor_ln68_15_fu_1247_p2 <= (tmp_146_fu_1151_p3 xor tmp_141_reg_2451);
    xor_ln68_16_fu_1252_p2 <= (tmp_147_fu_1217_p3 xor tmp_143_reg_2467);
    xor_ln68_17_fu_1257_p2 <= (xor_ln68_16_fu_1252_p2 xor xor_ln68_15_fu_1247_p2);
    xor_ln68_18_fu_1328_p2 <= (tmp_148_fu_1239_p3 xor tmp_143_reg_2467);
    xor_ln68_19_fu_1333_p2 <= (tmp_149_fu_1306_p3 xor tmp_145_fu_1130_p3);
    xor_ln68_1_fu_787_p2 <= (trunc_ln91_fu_737_p1 xor tmp_134_fu_741_p3);
    xor_ln68_20_fu_1339_p2 <= (xor_ln68_19_fu_1333_p2 xor xor_ln68_18_fu_1328_p2);
    xor_ln68_21_fu_1437_p2 <= (tmp_151_fu_1396_p3 xor tmp_150_fu_1359_p3);
    xor_ln68_22_fu_1443_p2 <= (tmp_153_fu_1410_p3 xor tmp_152_fu_1403_p3);
    xor_ln68_23_fu_1449_p2 <= (xor_ln68_22_fu_1443_p2 xor xor_ln68_21_fu_1437_p2);
    xor_ln68_24_fu_1533_p2 <= (tmp_155_fu_1498_p3 xor tmp_154_fu_1430_p3);
    xor_ln68_25_fu_1539_p2 <= (tmp_157_fu_1512_p3 xor tmp_156_fu_1505_p3);
    xor_ln68_26_fu_1545_p2 <= (xor_ln68_25_fu_1539_p2 xor xor_ln68_24_fu_1533_p2);
    xor_ln68_27_fu_1643_p2 <= (tmp_159_fu_1602_p3 xor tmp_158_fu_1565_p3);
    xor_ln68_28_fu_1649_p2 <= (tmp_161_fu_1616_p3 xor tmp_160_fu_1609_p3);
    xor_ln68_29_fu_1655_p2 <= (xor_ln68_28_fu_1649_p2 xor xor_ln68_27_fu_1643_p2);
    xor_ln68_2_fu_793_p2 <= (tmp_136_fu_757_p3 xor tmp_135_fu_749_p3);
    xor_ln68_30_fu_1747_p2 <= (tmp_163_fu_1704_p3 xor tmp_162_fu_1636_p3);
    xor_ln68_31_fu_1753_p2 <= (tmp_165_fu_1718_p3 xor tmp_164_fu_1711_p3);
    xor_ln68_32_fu_1759_p2 <= (xor_ln68_31_fu_1753_p2 xor xor_ln68_30_fu_1747_p2);
    xor_ln68_33_fu_1849_p2 <= (tmp_167_fu_1808_p3 xor tmp_166_reg_2569);
    xor_ln68_34_fu_1854_p2 <= (tmp_169_fu_1822_p3 xor tmp_168_fu_1815_p3);
    xor_ln68_35_fu_1860_p2 <= (xor_ln68_34_fu_1854_p2 xor xor_ln68_33_fu_1849_p2);
    xor_ln68_36_fu_1952_p2 <= (tmp_171_fu_1909_p3 xor tmp_170_fu_1842_p3);
    xor_ln68_37_fu_1958_p2 <= (tmp_173_fu_1923_p3 xor tmp_172_fu_1916_p3);
    xor_ln68_38_fu_1964_p2 <= (xor_ln68_37_fu_1958_p2 xor xor_ln68_36_fu_1952_p2);
    xor_ln68_39_fu_2054_p2 <= (tmp_175_fu_2013_p3 xor tmp_174_reg_2592);
    xor_ln68_3_fu_887_p2 <= (tmp_137_fu_779_p3 xor tmp_135_fu_749_p3);
    xor_ln68_40_fu_2059_p2 <= (tmp_177_fu_2027_p3 xor tmp_176_fu_2020_p3);
    xor_ln68_41_fu_2065_p2 <= (xor_ln68_40_fu_2059_p2 xor xor_ln68_39_fu_2054_p2);
    xor_ln68_42_fu_2157_p2 <= (tmp_179_fu_2114_p3 xor tmp_178_fu_2047_p3);
    xor_ln68_43_fu_2163_p2 <= (tmp_181_fu_2128_p3 xor tmp_180_fu_2121_p3);
    xor_ln68_44_fu_2169_p2 <= (xor_ln68_43_fu_2163_p2 xor xor_ln68_42_fu_2157_p2);
    xor_ln68_45_fu_2259_p2 <= (tmp_183_fu_2218_p3 xor tmp_182_reg_2615);
    xor_ln68_46_fu_2264_p2 <= (tmp_185_fu_2232_p3 xor tmp_184_fu_2225_p3);
    xor_ln68_47_fu_2270_p2 <= (xor_ln68_46_fu_2264_p2 xor xor_ln68_45_fu_2259_p2);
    xor_ln68_4_fu_893_p2 <= (tmp_139_fu_857_p3 xor tmp_138_fu_849_p3);
    xor_ln68_5_fu_899_p2 <= (xor_ln68_4_fu_893_p2 xor xor_ln68_3_fu_887_p2);
    xor_ln68_6_fu_982_p2 <= (tmp_140_reg_2429 xor tmp_138_reg_2418);
    xor_ln68_7_fu_986_p2 <= (tmp_141_fu_954_p3 xor tmp_136_reg_2402);
    xor_ln68_8_fu_991_p2 <= (xor_ln68_7_fu_986_p2 xor xor_ln68_6_fu_982_p2);
    xor_ln68_9_fu_1071_p2 <= (tmp_142_fu_975_p3 xor tmp_136_reg_2402);
    xor_ln68_fu_799_p2 <= (xor_ln68_2_fu_793_p2 xor xor_ln68_1_fu_787_p2);
    xor_ln94_10_fu_1790_p2 <= (tmp_166_reg_2569 xor ap_const_lv1_1);
    xor_ln94_11_fu_1891_p2 <= (tmp_170_fu_1842_p3 xor ap_const_lv1_1);
    xor_ln94_12_fu_1995_p2 <= (tmp_174_reg_2592 xor ap_const_lv1_1);
    xor_ln94_13_fu_2096_p2 <= (tmp_178_fu_2047_p3 xor ap_const_lv1_1);
    xor_ln94_14_fu_2200_p2 <= (tmp_182_reg_2615 xor ap_const_lv1_1);
    xor_ln94_15_fu_2301_p2 <= (tmp_186_fu_2252_p3 xor ap_const_lv1_1);
    xor_ln94_16_fu_824_p2 <= (icmp_ln94_fu_819_p2 xor ap_const_lv1_1);
    xor_ln94_17_fu_924_p2 <= (icmp_ln94_1_fu_919_p2 xor ap_const_lv1_1);
    xor_ln94_18_fu_1016_p2 <= (icmp_ln94_2_fu_1011_p2 xor ap_const_lv1_1);
    xor_ln94_19_fu_1106_p2 <= (icmp_ln94_3_fu_1101_p2 xor ap_const_lv1_1);
    xor_ln94_1_fu_930_p2 <= (tmp_140_fu_879_p3 xor ap_const_lv1_1);
    xor_ln94_20_fu_1192_p2 <= (icmp_ln94_4_fu_1187_p2 xor ap_const_lv1_1);
    xor_ln94_21_fu_1282_p2 <= (icmp_ln94_5_fu_1277_p2 xor ap_const_lv1_1);
    xor_ln94_22_fu_1371_p2 <= (icmp_ln94_6_fu_1366_p2 xor ap_const_lv1_1);
    xor_ln94_23_fu_1474_p2 <= (icmp_ln94_7_fu_1469_p2 xor ap_const_lv1_1);
    xor_ln94_24_fu_1577_p2 <= (icmp_ln94_8_fu_1572_p2 xor ap_const_lv1_1);
    xor_ln94_25_fu_1680_p2 <= (icmp_ln94_9_fu_1675_p2 xor ap_const_lv1_1);
    xor_ln94_26_fu_1784_p2 <= (icmp_ln94_10_fu_1779_p2 xor ap_const_lv1_1);
    xor_ln94_27_fu_1885_p2 <= (icmp_ln94_11_fu_1880_p2 xor ap_const_lv1_1);
    xor_ln94_28_fu_1989_p2 <= (icmp_ln94_12_fu_1984_p2 xor ap_const_lv1_1);
    xor_ln94_29_fu_2090_p2 <= (icmp_ln94_13_fu_2085_p2 xor ap_const_lv1_1);
    xor_ln94_2_fu_1022_p2 <= (tmp_142_fu_975_p3 xor ap_const_lv1_1);
    xor_ln94_30_fu_2194_p2 <= (icmp_ln94_14_fu_2189_p2 xor ap_const_lv1_1);
    xor_ln94_31_fu_2295_p2 <= (icmp_ln94_15_fu_2290_p2 xor ap_const_lv1_1);
    xor_ln94_3_fu_1112_p2 <= (tmp_144_fu_1063_p3 xor ap_const_lv1_1);
    xor_ln94_4_fu_1198_p2 <= (tmp_146_fu_1151_p3 xor ap_const_lv1_1);
    xor_ln94_5_fu_1288_p2 <= (tmp_148_fu_1239_p3 xor ap_const_lv1_1);
    xor_ln94_6_fu_1377_p2 <= (tmp_150_fu_1359_p3 xor ap_const_lv1_1);
    xor_ln94_7_fu_1480_p2 <= (tmp_154_fu_1430_p3 xor ap_const_lv1_1);
    xor_ln94_8_fu_1583_p2 <= (tmp_158_fu_1565_p3 xor ap_const_lv1_1);
    xor_ln94_9_fu_1686_p2 <= (tmp_162_fu_1636_p3 xor ap_const_lv1_1);
    xor_ln94_fu_830_p2 <= (tmp_137_fu_779_p3 xor ap_const_lv1_1);
    zext_ln1287_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1311_1_fu_651_p1),79));
    zext_ln339_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_fu_588_p4),9));
    zext_ln662_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_133_fu_673_p3),32));
    zext_ln682_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_V_fu_638_p4),79));
    zext_ln96_fu_731_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_389),64));
end behav;
