// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dut_HH_
#define _dut_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "mlp_xcel.h"

namespace ap_rtl {

struct dut : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<27> > strm_in_V_V_dout;
    sc_in< sc_logic > strm_in_V_V_empty_n;
    sc_out< sc_logic > strm_in_V_V_read;
    sc_out< sc_lv<27> > strm_out_V_V_din;
    sc_in< sc_logic > strm_out_V_V_full_n;
    sc_out< sc_logic > strm_out_V_V_write;


    // Module declarations
    dut(sc_module_name name);
    SC_HAS_PROCESS(dut);

    ~dut();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mlp_xcel* grp_mlp_xcel_fu_388;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > strm_in_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln23_fu_655_p2;
    sc_signal< sc_logic > strm_out_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<4> > i_fu_661_p2;
    sc_signal< sc_lv<4> > i_reg_813;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<27> > tmp_V_load_reg_818;
    sc_signal< sc_lv<27> > tmp_V_2_load_reg_823;
    sc_signal< sc_lv<27> > tmp_V_3_load_reg_828;
    sc_signal< sc_lv<27> > tmp_V_4_load_reg_833;
    sc_signal< sc_lv<27> > tmp_V_5_load_reg_838;
    sc_signal< sc_lv<27> > tmp_V_6_load_reg_843;
    sc_signal< sc_lv<27> > tmp_V_7_load_reg_848;
    sc_signal< sc_lv<27> > tmp_V_8_load_reg_853;
    sc_signal< sc_lv<27> > tmp_V_9_load_reg_858;
    sc_signal< sc_lv<27> > mean_output_V_reg_863;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > grp_mlp_xcel_fu_388_ap_ready;
    sc_signal< sc_logic > grp_mlp_xcel_fu_388_ap_done;
    sc_signal< sc_lv<27> > variance_output_V_reg_868;
    sc_signal< sc_logic > grp_mlp_xcel_fu_388_ap_start;
    sc_signal< sc_logic > grp_mlp_xcel_fu_388_ap_idle;
    sc_signal< sc_lv<27> > grp_mlp_xcel_fu_388_ap_return_0;
    sc_signal< sc_lv<27> > grp_mlp_xcel_fu_388_ap_return_1;
    sc_signal< sc_lv<4> > ap_phi_mux_i_0_phi_fu_381_p4;
    sc_signal< sc_lv<4> > i_0_reg_377;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_mlp_xcel_fu_388_ap_start_reg;
    sc_signal< bool > ap_block_state2_ignore_call9;
    sc_signal< sc_lv<27> > tmp_V_fu_328;
    sc_signal< sc_lv<27> > tmp_V_2_fu_332;
    sc_signal< sc_lv<27> > tmp_V_3_fu_336;
    sc_signal< sc_lv<27> > tmp_V_4_fu_340;
    sc_signal< sc_lv<27> > tmp_V_5_fu_344;
    sc_signal< sc_lv<27> > tmp_V_6_fu_348;
    sc_signal< sc_lv<27> > tmp_V_7_fu_352;
    sc_signal< sc_lv<27> > tmp_V_8_fu_356;
    sc_signal< sc_lv<27> > tmp_V_9_fu_360;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<4> ap_const_lv4_9;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_state2();
    void thread_ap_block_state2_ignore_call9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_i_0_phi_fu_381_p4();
    void thread_ap_ready();
    void thread_grp_mlp_xcel_fu_388_ap_start();
    void thread_i_fu_661_p2();
    void thread_icmp_ln23_fu_655_p2();
    void thread_strm_in_V_V_blk_n();
    void thread_strm_in_V_V_read();
    void thread_strm_out_V_V_blk_n();
    void thread_strm_out_V_V_din();
    void thread_strm_out_V_V_write();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
